-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Caster-aura requirements ([spellID] = aura spellID the player
-- must have for the spell to be castable). The queue sinks these while
-- the required aura is absent.
-- GENERATED by tools/gen_aura_requirements.py from client data build 12.1.0.68301.
-- Do not hand-edit.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterAuraRequirements then return end

SpellDB.RegisterAuraRequirements({
[5143]=263725,  -- Arcane Missiles (requires Clearcasting)
[91778]=63560,  -- Sweeping Claws (requires Dark Transformation)
[91797]=63560,  -- Monstrous Blow (requires Dark Transformation)
[91802]=63560,  -- Shambling Rush (requires Dark Transformation)
[91837]=63560,  -- Putrid Bulwark (requires Dark Transformation)
[119898]=119904,  -- Command Demon (requires Override Command Demon)
[152175]=196742,  -- Whirling Dragon Punch (requires Whirling Dragon Punch)
[175686]=1,  -- Stopping Power (requires Word of Recall (OLD))
[196277]=296553,  -- Implosion (requires Wild Imp)
[196447]=228312,  -- Channel Demonfire (requires Immolate)
[205065]=194249,  -- Void Torrent (requires Voidform)
[205406]=214502,  -- Sheilun's Gift (requires Sheilun's Gift)
[212337]=63560,  -- Powerful Smash (requires Dark Transformation)
[212338]=63560,  -- Vile Gas (requires Dark Transformation)
[212383]=63560,  -- Gastric Bloat (requires Dark Transformation)
[212470]=63560,  -- Flesh Hook (requires Dark Transformation)
[247454]=203981,  -- Spirit Bomb (requires Soul Fragments)
[264057]=428344,  -- Soul Strike (requires Soul Strike)
[264130]=296553,  -- Power Siphon (requires Wild Imp)
[314955]=316910,  -- Sanity Restoration Orb (requires Available Sanity Orbs)
[375982]=466622,  -- Primordial Wave (requires Fire Nova)
[376743]=386449,  -- Surge Forward (requires Surge Forward)
[376744]=386451,  -- Skyward Ascent (requires Skyward Ascent)
[386256]=386251,  -- Summon Soulkeeper (requires Tormented Soul)
[389713]=62388,  -- Reflection (requires Teleport Range)
[403092]=372773,  -- Aerial Halt (requires Dragonrider Energy)
[403216]=369536,  -- Aerial Halt (requires Soar)
[425782]=372773,  -- Second Wind (requires Dragonrider Energy)
[436521]=424143,  -- Extract Gem (requires WoW Remix: Mists of Pandaria)
[436524]=424143,  -- Unraveling Sands (requires WoW Remix: Mists of Pandaria)
[437545]=1234,  -- Test (requires Joe's God Mode)
[1215078]=1215077,  -- Boost (requires Boosting Unlocked)
[1232808]=1213439,  -- Unraveling Sands (requires WoW Remix: Legion)
[1244258]=1244393,  -- Chomp (requires Chomp Enabler)
})
