-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Caster-aura requirements ([spellID] = aura spellID the player
-- must have for the spell to be castable). The queue sinks these while
-- the required aura is absent.
-- GENERATED by tools/gen_aura_requirements.py from client data build 12.1.0.68301.
-- Do not hand-edit.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterAuraRequirements then return end

SpellDB.RegisterAuraRequirements({
[5143]=263725,
[91778]=63560,
[91797]=63560,
[91802]=63560,
[91837]=63560,
[119898]=119904,
[152175]=196742,
[175686]=1,
[196277]=296553,
[196447]=228312,
[205065]=194249,
[205406]=214502,
[212337]=63560,
[212338]=63560,
[212383]=63560,
[212470]=63560,
[247454]=203981,
[264057]=428344,
[264130]=296553,
[314955]=316910,
[375982]=466622,
[376743]=386449,
[376744]=386451,
[386256]=386251,
[389713]=62388,
[403092]=372773,
[403216]=369536,
[425782]=372773,
[436521]=424143,
[436524]=424143,
[437545]=1234,
[1215078]=1215077,
[1232808]=1213439,
[1244258]=1244393,
})
