-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Aura max-stack data ([spellID] = maxStacks, stacking auras only).
-- A stacking aura is never 'unique already active' - client-data veto for
-- RedundancyFilter's unique-aura classification.
-- GENERATED by tools/gen_aura_stacks.py from client data build 12.1.0.68301.
-- Do not hand-edit.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterAuraStacks then return end

SpellDB.RegisterAuraStacks({
[974]=9,
[980]=8,
[6360]=11,
[20243]=3,
[52127]=9,
[73685]=2,
[86678]=5,
[108839]=3,
[115236]=3,
[137639]=2,
[157982]=5,
[191034]=20,
[191634]=4,
[210714]=2,
[210726]=4,
[211088]=10,
[224968]=4,
[231895]=10,
[260708]=18,
[316440]=3,
[323546]=99,
[323654]=30,
[323764]=99,
[325013]=99,
[370537]=3,
[383334]=5,
[384027]=2,
[386738]=2,
[387638]=3,
[389539]=15,
[391528]=99,
[400278]=3,
[414273]=2,
[472433]=2,
[1223131]=99,
[1233181]=20,
[1259790]=99,
[1269312]=2,
[1271387]=6,
[1271466]=6,
})
