-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Hard shapeshift requirements ([spellID] = stance mask, bit N =
-- usable in form ID N+1). Consumed via SpellDB.IsSpellFormGated to sink or
-- hide form-gated abilities without secret-value reads.
-- GENERATED by tools/gen_form_requirements.py from client data build 12.1.0.68301.
-- Do not hand-edit.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterFormRequirements then return end

SpellDB.RegisterFormRequirements({
[1079]=1,
[1178]=16,
[1822]=1,
[3025]=1,
[5221]=1,
[5225]=1,
[6795]=16,
[6807]=16,
[20719]=1,
[22568]=1,
[22570]=1,
[22842]=16,
[33917]=16,
[77758]=16,
[106830]=1,
[106839]=17,
[135288]=16,
[192081]=16,
[200851]=16,
[202028]=17,
[210065]=1,
[210722]=1,
[213764]=17,
[236716]=16,
[274837]=1,
[285381]=1,
[400254]=16,
[1243807]=1,
[1244258]=1,
[1253799]=16,
})

-- Stealth-required spells (stealth-only stance masks). Gated at runtime
-- with IsStealthed() + stealth-window auras, never statically.
if SpellDB.RegisterStealthRequirements then
SpellDB.RegisterStealthRequirements({
[921]=true,
[1833]=true,
[6770]=true,
[8676]=true,
[114018]=true,
})
end
