-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Hard shapeshift requirements ([spellID] = stance mask, bit N =
-- usable in form ID N+1). Consumed via SpellDB.IsSpellFormGated to sink or
-- hide form-gated abilities without secret-value reads.
-- GENERATED by tools/gen_form_requirements.py from client data build 12.1.0.68301.
-- Do not hand-edit.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterFormRequirements then return end

SpellDB.RegisterFormRequirements({
[1079]=1,  -- Rip
[1178]=16,  -- Bear Form Passive
[1822]=1,  -- Rake
[3025]=1,  -- Cat Form
[5221]=1,  -- Shred
[5225]=1,  -- Track Humanoids
[6795]=16,  -- Growl
[6807]=16,  -- Maul
[20719]=1,  -- Feline Grace
[22568]=1,  -- Ferocious Bite
[22570]=1,  -- Maim
[22842]=16,  -- Frenzied Regeneration
[33917]=16,  -- Mangle
[77758]=16,  -- Thrash
[106830]=1,  -- Thrash
[106839]=17,  -- Skull Bash
[135288]=16,  -- Tooth and Claw
[192081]=16,  -- Ironfur
[200851]=16,  -- Rage of the Sleeper
[202028]=17,  -- Brutal Slash
[210065]=1,  -- Track Beasts
[210722]=1,  -- Ashamane's Frenzy
[213764]=17,  -- Swipe
[236716]=16,  -- Strength of the Wild
[274837]=1,  -- Feral Frenzy
[285381]=1,  -- Primal Wrath
[400254]=16,  -- Raze
[1243807]=1,  -- Frantic Frenzy
[1244258]=1,  -- Chomp
[1253799]=16,  -- Sundering Roar
})

-- Stealth-required spells (stealth-only stance masks). Gated at runtime
-- with IsStealthed() + stealth-window auras, never statically.
if SpellDB.RegisterStealthRequirements then
SpellDB.RegisterStealthRequirements({
[921]=true,  -- Pick Pocket
[1833]=true,  -- Cheap Shot
[6770]=true,  -- Sap
[8676]=true,  -- Ambush
[114018]=true,  -- Shroud of Concealment
})
end
