-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
-- JustAC: Pre-combat buff consumables (flasks, food, augment runes, weapon enchants).
--
-- GENERATED by tools/gen_precombat_buffs.py from wago.tools DB2 dumps - do not hand-edit
-- the generated categories. Re-run each major patch (see the script header). Items are
-- discovered by item class/subclass and their persistent buff aura is resolved from the
-- effect chain; `buff` is the aura spellID the addon checks for, `stat` is what it grants.
--
-- Source-aware: generated entries are bag items (source defaults to "item"). Toys
-- (source = "toy") and class self-buffs (source = "spell") are hand-added below the
-- HAND-CURATED marker and are preserved across regeneration only if you keep them there.
local SpellDB = LibStub("JustAC-SpellDB", true)
if not SpellDB or not SpellDB.RegisterPrecombatBuffs then return end

SpellDB.RegisterPrecombatBuffs({
    flask = {
        -- Midnight / current
        { id = 241320, buff = 1235057, stat = "versatility" },  -- Flask of Thalassian Resistance
        { id = 241324, buff = 1235110, stat = "haste" },  -- Flask of the Blood Knights
        { id = 241322, buff = 1235108, stat = "mastery" },  -- Flask of the Magisters
        { id = 241326, buff = 1235111, stat = "crit" },  -- Flask of the Shattered Sun
        { id = 245926, buff = 1235057, stat = "versatility" },  -- Fleeting Flask of Thalassian Resistance
        { id = 245931, buff = 1235110, stat = "haste" },  -- Fleeting Flask of the Blood Knights
        { id = 245933, buff = 1235108, stat = "mastery" },  -- Fleeting Flask of the Magisters
        { id = 245929, buff = 1235111, stat = "crit" },  -- Fleeting Flask of the Shattered Sun
        { id = 241321, buff = 1235057, stat = "versatility" },  -- Flask of Thalassian Resistance
        { id = 241325, buff = 1235110, stat = "haste" },  -- Flask of the Blood Knights
        { id = 241323, buff = 1235108, stat = "mastery" },  -- Flask of the Magisters
        { id = 241327, buff = 1235111, stat = "crit" },  -- Flask of the Shattered Sun
        { id = 245927, buff = 1235057, stat = "versatility" },  -- Fleeting Flask of Thalassian Resistance
        { id = 245930, buff = 1235110, stat = "haste" },  -- Fleeting Flask of the Blood Knights
        { id = 245932, buff = 1235108, stat = "mastery" },  -- Fleeting Flask of the Magisters
        { id = 245928, buff = 1235111, stat = "crit" },  -- Fleeting Flask of the Shattered Sun
        -- Dragonflight / TWW
        { id = 212283, buff = 432021, stat = "crit" },  -- Flask of Alchemical Chaos
        { id = 212271, buff = 431971, stat = "crit" },  -- Flask of Tempered Aggression
        { id = 212280, buff = 431974, stat = "mastery" },  -- Flask of Tempered Mastery
        { id = 212274, buff = 431972, stat = "haste" },  -- Flask of Tempered Swiftness
        { id = 212277, buff = 431973, stat = "versatility" },  -- Flask of Tempered Versatility
        { id = 212741, buff = 432021, stat = "crit" },  -- Fleeting Flask of Alchemical Chaos
        { id = 212728, buff = 431971, stat = "crit" },  -- Fleeting Flask of Tempered Aggression
        { id = 212738, buff = 431974, stat = "mastery" },  -- Fleeting Flask of Tempered Mastery
        { id = 212731, buff = 431972, stat = "haste" },  -- Fleeting Flask of Tempered Swiftness
        { id = 212734, buff = 431973, stat = "versatility" },  -- Fleeting Flask of Tempered Versatility
        { id = 212777, buff = 431971, stat = "crit" },  -- zzOldFleeting Flask of Tempered Aggression
        { id = 212282, buff = 432021, stat = "crit" },  -- Flask of Alchemical Chaos
        { id = 212270, buff = 431971, stat = "crit" },  -- Flask of Tempered Aggression
        { id = 212279, buff = 431974, stat = "mastery" },  -- Flask of Tempered Mastery
        { id = 212273, buff = 431972, stat = "haste" },  -- Flask of Tempered Swiftness
        { id = 212276, buff = 431973, stat = "versatility" },  -- Flask of Tempered Versatility
        { id = 212740, buff = 432021, stat = "crit" },  -- Fleeting Flask of Alchemical Chaos
        { id = 212727, buff = 431971, stat = "crit" },  -- Fleeting Flask of Tempered Aggression
        { id = 212736, buff = 431974, stat = "mastery" },  -- Fleeting Flask of Tempered Mastery
        { id = 212730, buff = 431972, stat = "haste" },  -- Fleeting Flask of Tempered Swiftness
        { id = 212733, buff = 431973, stat = "versatility" },  -- Fleeting Flask of Tempered Versatility
        { id = 212776, buff = 431971, stat = "crit" },  -- zzOldFleeting Flask of Tempered Aggression
        { id = 212281, buff = 432021, stat = "crit" },  -- Flask of Alchemical Chaos
        { id = 212269, buff = 431971, stat = "crit" },  -- Flask of Tempered Aggression
        { id = 212278, buff = 431974, stat = "mastery" },  -- Flask of Tempered Mastery
        { id = 212272, buff = 431972, stat = "haste" },  -- Flask of Tempered Swiftness
        { id = 212275, buff = 431973, stat = "versatility" },  -- Flask of Tempered Versatility
        { id = 212739, buff = 432021, stat = "crit" },  -- Fleeting Flask of Alchemical Chaos
        { id = 212725, buff = 431971, stat = "crit" },  -- Fleeting Flask of Tempered Aggression
        { id = 212735, buff = 431974, stat = "mastery" },  -- Fleeting Flask of Tempered Mastery
        { id = 212729, buff = 431972, stat = "haste" },  -- Fleeting Flask of Tempered Swiftness
        { id = 212732, buff = 431973, stat = "versatility" },  -- Fleeting Flask of Tempered Versatility
        { id = 212775, buff = 431971, stat = "crit" },  -- zzOldFleeting Flask of Tempered Aggression
        -- Shadowlands
        { id = 191350, buff = 371186 },  -- Charged Phial of Alacrity
        { id = 204669, buff = 371186 },  -- Fleeting Charged Phial of Alacrity
        { id = 204666, buff = 371172, stat = "versatility" },  -- Fleeting Phial of Tepid Versatility
        { id = 191341, buff = 371172, stat = "versatility" },  -- Phial of Tepid Versatility
        { id = 191349, buff = 371186 },  -- Charged Phial of Alacrity
        { id = 204668, buff = 371186 },  -- Fleeting Charged Phial of Alacrity
        { id = 204665, buff = 371172, stat = "versatility" },  -- Fleeting Phial of Tepid Versatility
        { id = 191340, buff = 371172, stat = "versatility" },  -- Phial of Tepid Versatility
        { id = 191348, buff = 371186 },  -- Charged Phial of Alacrity
        { id = 204667, buff = 371186 },  -- Fleeting Charged Phial of Alacrity
        { id = 204664, buff = 371172, stat = "versatility" },  -- Fleeting Phial of Tepid Versatility
        { id = 191339, buff = 371172, stat = "versatility" },  -- Phial of Tepid Versatility
        { id = 195580, buff = 379076, stat = "crit" },  -- Suspicious Bottle
        -- Battle for Azeroth
        { id = 171280, buff = 307166, stat = "primary" },  -- Eternal Flask
        { id = 171276, buff = 307185, stat = "primary" },  -- Spectral Flask of Power
        { id = 171278, buff = 307187, stat = "stamina" },  -- Spectral Flask of Stamina
        -- Legion
        { id = 152639, buff = 251837, stat = "intellect" },  -- Flask of Endless Fathoms
        { id = 152638, buff = 251836, stat = "agility" },  -- Flask of the Currents
        { id = 152641, buff = 251839, stat = "strength" },  -- Flask of the Undertow
        { id = 152640, buff = 251838, stat = "stamina" },  -- Flask of the Vast Horizon
        { id = 168652, buff = 298837, stat = "intellect" },  -- Greater Flask of Endless Fathoms
        { id = 168651, buff = 298836, stat = "agility" },  -- Greater Flask of the Currents
        { id = 168654, buff = 298841, stat = "strength" },  -- Greater Flask of the Undertow
        { id = 168653, buff = 298839, stat = "stamina" },  -- Greater Flask of the Vast Horizon
        -- Warlords of Draenor
        { id = 127850, buff = 188035, stat = "stamina" },  -- Flask of Ten Thousand Scars
        { id = 127849, buff = 188034, stat = "strength" },  -- Flask of the Countless Armies
        { id = 127848, buff = 188033, stat = "agility" },  -- Flask of the Seventh Demon
        { id = 127847, buff = 188031, stat = "intellect" },  -- Flask of the Whispered Pact
        -- Mists of Pandaria
        { id = 109145, buff = 156073, stat = "agility" },  -- Draenic Agility Flask
        { id = 109147, buff = 156070, stat = "intellect" },  -- Draenic Intellect Flask
        { id = 109152, buff = 156077, stat = "stamina" },  -- Draenic Stamina Flask
        { id = 109148, buff = 156071, stat = "strength" },  -- Draenic Strength Flask
        { id = 109153, buff = 156064, stat = "agility" },  -- Greater Draenic Agility Flask
        { id = 109155, buff = 156079, stat = "intellect" },  -- Greater Draenic Intellect Flask
        { id = 109160, buff = 156084, stat = "stamina" },  -- Greater Draenic Stamina Flask
        { id = 109156, buff = 156080, stat = "strength" },  -- Greater Draenic Strength Flask
        -- Cataclysm
        { id = 76086, buff = 105693, stat = "versatility" },  -- Flask of Falling Leaves
        { id = 76084, buff = 105689, stat = "agility" },  -- Flask of Spring Blossoms
        { id = 76088, buff = 105696, stat = "strength" },  -- Flask of Winter's Bite
        { id = 76087, buff = 105694, stat = "stamina" },  -- Flask of the Earth
        { id = 76085, buff = 105691, stat = "intellect" },  -- Flask of the Warm Sun
        -- Wrath
        { id = 67438, buff = 94160, stat = "versatility" },  -- Flask of Flowing Water
        { id = 58085, buff = 79469, stat = "stamina" },  -- Flask of Steelskin
        { id = 58088, buff = 79472, stat = "strength" },  -- Flask of Titanic Strength
        { id = 58086, buff = 79470, stat = "intellect" },  -- Flask of the Draconic Mind
        { id = 58087, buff = 79471, stat = "agility" },  -- Flask of the Winds
        -- Burning Crusade
        { id = 46377, buff = 53760 },  -- Flask of Endless Rage
        { id = 46378, buff = 54212, stat = "versatility" },  -- Flask of Pure Mojo
        -- Classic
        { id = 22851, buff = 28518 },  -- Flask of Fortification
        { id = 22853, buff = 28519, stat = "versatility" },  -- Flask of Mighty Versatility
        { id = 22854, buff = 28520 },  -- Flask of Relentless Assault
        { id = 32898, buff = 41607 },  -- Shattrath Flask of Fortification
        { id = 32899, buff = 41605, stat = "versatility" },  -- Shattrath Flask of Mighty Restoration
        { id = 32901, buff = 41606 },  -- Shattrath Flask of Relentless Assault
        { id = 32599, buff = 40577, stat = "agility" },  -- Unstable Flask of the Bandit
        { id = 32598, buff = 40580, stat = "agility" },  -- Unstable Flask of the Beast
        { id = 32596, buff = 40582, stat = "intellect" },  -- Unstable Flask of the Elder
        { id = 32600, buff = 40586, stat = "intellect" },  -- Unstable Flask of the Physician
        { id = 32597, buff = 40587, stat = "crit" },  -- Unstable Flask of the Soldier
        { id = 32601, buff = 40588, stat = "intellect" },  -- Unstable Flask of the Sorcerer
        -- Classic
        { id = 45006, buff = 53760 },  -- Jillian's Tonic of Endless Rage
        { id = 45007, buff = 54212, stat = "versatility" },  -- Jillian's Tonic of Pure Mojo
        { id = 32764, buff = 28518 },  -- Flaskataur's Celestial Brew
        { id = 32766, buff = 28519, stat = "versatility" },  -- Flaskataur's Flask of Flaskocity
        { id = 32765, buff = 28520 },  -- Flaskataur's Tears
        { id = 13511, buff = 17627, stat = "intellect" },  -- Flask of Distilled Wisdom
    },
    food = {
        -- Midnight / current
        { id = 245573, buff = 1239149, stat = "versatility" },  -- Salmon
        -- Dragonflight / TWW
        { id = 225592, buff = 455369 },  -- Exquisitely Eviscerated Muscle
        { id = 222740, buff = 382235, stat = "stamina" },  -- Hearty Meals
        { id = 222745, buff = 462148 },  -- Pep-In-Your-Step
        -- Shadowlands
        { id = 197783, buff = 382153, stat = "haste+versatility" },  -- Aromatic Seafood Platter
        { id = 197788, buff = 382234, stat = "stamina" },  -- Braised Bruffalon Brisket
        { id = 197774, buff = 382230, stat = "stamina" },  -- Charred Hornswog Steaks
        { id = 204072, buff = 396092, stat = "primary" },  -- Deviously Deviled Eggs
        { id = 197792, buff = 396092, stat = "primary" },  -- Fated Fortune Cookie
        { id = 197782, buff = 382152, stat = "crit+haste" },  -- Feisty Fish Sticks
        { id = 197779, buff = 382146, stat = "crit" },  -- Filet of Fangs
        { id = 202290, buff = 398458, stat = "crit+haste+mastery+versatility" },  -- Firewater Sorbet
        { id = 205684, buff = 410276, stat = "crit+haste+mastery+versatility" },  -- Forbidden Flounder
        { id = 197787, buff = 382157, stat = "mastery+versatility" },  -- Great Cerulean Sea
        { id = 197777, buff = 382246, stat = "stamina" },  -- Hopefully Healthy
        { id = 197785, buff = 382155, stat = "crit+versatility" },  -- Revenge, Served Cold
        { id = 197789, buff = 382235, stat = "stamina" },  -- Riverside Picnic
        { id = 197790, buff = 382236, stat = "stamina" },  -- Roast Duck Delight
        { id = 197781, buff = 382150, stat = "mastery" },  -- Salt-Baked Fishcake
        { id = 197791, buff = 382247, stat = "stamina" },  -- Salted Meat Mash
        { id = 197775, buff = 382231, stat = "stamina" },  -- Scrambled Basilisk Eggs
        { id = 197780, buff = 382149, stat = "versatility" },  -- Seamoth Surprise
        { id = 197784, buff = 382154, stat = "haste+mastery" },  -- Sizzling Seafood Medley
        { id = 197786, buff = 382156, stat = "crit+mastery" },  -- Thousandbone Tongueslicer
        { id = 197776, buff = 382232, stat = "stamina" },  -- Thrice-Spiced Mammoth Kabob
        { id = 197778, buff = 382145, stat = "haste" },  -- Timely Demise
        -- Battle for Azeroth
        { id = 182592, buff = 308434, stat = "crit" },  -- Infused Endmire Fruit
        { id = 190953, buff = 327707, stat = "stamina" },  -- Protofruit Flesh
        { id = 172069, buff = 308525, stat = "stamina" },  -- Banana Beef Pudding
        { id = 172040, buff = 308430, stat = "crit" },  -- Butterscotch Marinated Ribs
        { id = 172044, buff = 308474, stat = "haste" },  -- Cinnamon Bonefish Stew
        { id = 172049, buff = 308506, stat = "mastery" },  -- Iridescent Ravioli with Apple Sauce
        { id = 172048, buff = 308504, stat = "mastery" },  -- Meaty Apple Dumplings
        { id = 172068, buff = 308520, stat = "stamina" },  -- Pickled Meat Smoothie
        { id = 172041, buff = 308434, stat = "crit" },  -- Spinefin Souffle and Fries
        { id = 172051, buff = 308514, stat = "versatility" },  -- Steak a la Mode
        { id = 172050, buff = 308509, stat = "versatility" },  -- Sweet Silvergill Sausages
        { id = 172045, buff = 308488, stat = "haste" },  -- Tenebrous Crown Roast Aspic
        -- Legion
        { id = 154882, buff = 257410, stat = "crit" },  -- Honey-Glazed Haunches
        { id = 168232, buff = 296455, stat = "primary" },  -- Murloco's "Fish" Tacos
        { id = 154888, buff = 257420, stat = "mastery" },  -- Sailor's Pie
        { id = 166344, buff = 288075, stat = "stamina" },  -- Seasoned Steak and Potatoes
        { id = 154886, buff = 257424, stat = "versatility" },  -- Spiced Snapper
        { id = 163081, buff = 257422, stat = "versatility" },  -- Spicy Barbecued Buzzard Wing
        { id = 154884, buff = 257415, stat = "haste" },  -- Swamp Fish 'n Chips
        { id = 168311, buff = 297035, stat = "mastery" },  -- Abyssal-Fried Rissole
        { id = 168313, buff = 297034, stat = "haste" },  -- Baked Port Tato
        { id = 168314, buff = 297037, stat = "versatility" },  -- Bil'Tong
        { id = 168312, buff = 297040, stat = "stamina" },  -- Fragrant Kakavia
        { id = 154881, buff = 257408, stat = "crit" },  -- Kul Tiramisu
        { id = 154887, buff = 257418, stat = "mastery" },  -- Loa Loaf
        { id = 168310, buff = 297039, stat = "crit" },  -- Mech-Dowel's "Big Mech"
        { id = 154885, buff = 257422, stat = "versatility" },  -- Mon'Dazi
        { id = 154883, buff = 257413, stat = "haste" },  -- Ravenberry Tarts
        { id = 166343, buff = 288074, stat = "stamina" },  -- Wild Berry Bread
        { id = 162117, buff = 274375, stat = "versatility" },  -- Marie's Famous Cookies
        { id = 167832, buff = 294365 },  -- Canned Minnows
        -- Warlords of Draenor
        { id = 133571, buff = 225603, stat = "haste" },  -- Azshari Salad
        { id = 133567, buff = 225599, stat = "mastery" },  -- Barracuda Mrglgagh
        { id = 143635, buff = 225598, stat = "haste" },  -- Hasty Hummus
        { id = 133568, buff = 225600, stat = "versatility" },  -- Koi-Scented Stormray
        { id = 133565, buff = 225597, stat = "crit" },  -- Leybeque Ribs
        { id = 133572, buff = 225604, stat = "mastery" },  -- Nightborne Delicacy Platter
        { id = 133573, buff = 225605, stat = "versatility" },  -- Seed-Battered Fish Plate
        { id = 133566, buff = 225598, stat = "haste" },  -- Suramar Surf and Turf
        { id = 133570, buff = 225602, stat = "crit" },  -- The Hungry Magister
        { id = 133561, buff = 201330, stat = "haste" },  -- Deep-Fried Mossgill
        { id = 133563, buff = 201334, stat = "versatility" },  -- Faronaar Fizz
        { id = 133562, buff = 201332, stat = "mastery" },  -- Pickled Stormray
        { id = 133557, buff = 201223, stat = "crit" },  -- Salt and Pepper Shank
        -- Mists of Pandaria
        { id = 111433, buff = 160724, stat = "crit" },  -- Blackrock Ham
        { id = 111436, buff = 160793, stat = "mastery" },  -- Braised Riverbeast
        { id = 111438, buff = 160839, stat = "versatility" },  -- Clefthoof Sausages
        { id = 111444, buff = 160793, stat = "mastery" },  -- Fat Sleeper Cakes
        { id = 111445, buff = 160832, stat = "crit" },  -- Fiery Calamari
        { id = 111441, buff = 160724, stat = "crit" },  -- Grilled Gulper
        { id = 111431, buff = 160600, stat = "stamina" },  -- Hearty Elekk Steak
        { id = 111434, buff = 160726, stat = "haste" },  -- Pan-Seared Talbuk
        { id = 111437, buff = 160832, stat = "crit" },  -- Rylak Crepes
        { id = 111446, buff = 160839, stat = "versatility" },  -- Skulker Chowder
        { id = 111439, buff = 160600, stat = "stamina" },  -- Steamed Scorpion
        { id = 111442, buff = 160726, stat = "haste" },  -- Sturgeon Stew
        -- Cataclysm
        { id = 74646, buff = 104272, stat = "strength" },  -- Black Pepper Ribs and Shrimp
        { id = 74656, buff = 104283, stat = "stamina" },  -- Chun Tian Spring Rolls
        { id = 75038, buff = 105226, stat = "strength" },  -- Mad Brewer's Breakfast
        { id = 74650, buff = 104277, stat = "intellect" },  -- Mogu Fish Stew
        { id = 74648, buff = 104275, stat = "agility" },  -- Sea Mist Rice Noodles
        { id = 74653, buff = 104280, stat = "versatility" },  -- Steamed Crab Surprise
        { id = 74649, buff = 104276, stat = "intellect" },  -- Braised Turtle
        { id = 74642, buff = 104267, stat = "strength" },  -- Charbroiled Tiger Steak
        { id = 74645, buff = 104271, stat = "strength" },  -- Eternal Blossom Fish
        { id = 74652, buff = 104279, stat = "versatility" },  -- Fire Spirit Salmon
        { id = 86069, buff = 125108, stat = "haste" },  -- Rice Pudding
        { id = 74643, buff = 104273, stat = "agility" },  -- Sauteed Carrots
        { id = 74651, buff = 104278, stat = "versatility" },  -- Shrimp Dumplings
        { id = 74644, buff = 104264, stat = "intellect" },  -- Swirling Mist Soup
        { id = 74655, buff = 104282, stat = "stamina" },  -- Twin Fish Platter
        { id = 74647, buff = 104274, stat = "agility" },  -- Valley Stir Fry
        { id = 74654, buff = 104281, stat = "stamina" },  -- Wildfowl Roast
        -- Wrath
        { id = 62654, buff = 87634, stat = "haste" },  -- Lavascale Fillet
        -- Classic
        { id = 202401, buff = 19705, stat = "stamina" },  -- Cactus Apple Surprise
        { id = 133576, buff = 201670 },  -- Bear Tartare
        { id = 143634, buff = 225597, stat = "crit" },  -- Critical Catfish
        { id = 143633, buff = 225599, stat = "mastery" },  -- Masterful Mana Buns
        { id = 111449, buff = 160889, stat = "crit" },  -- Blackrock Barbecue
        { id = 122348, buff = 180748, stat = "haste" },  -- Buttered Sturgeon
        { id = 111453, buff = 160900, stat = "crit" },  -- Calamari Crepes
        { id = 111435, buff = 160778, stat = "versatility" },  -- Clefhoof Pot Roast
        { id = 111450, buff = 160893, stat = "haste" },  -- Frosty Stew
        { id = 118268, buff = 160793, stat = "mastery" },  -- Fuzzy Pear
        { id = 118272, buff = 160724, stat = "crit" },  -- Giant Nagrand Cherry
        { id = 111454, buff = 160902, stat = "versatility" },  -- Gorgrond Chowder
        { id = 118269, buff = 160832, stat = "crit" },  -- Greenskin Apple
        { id = 118271, buff = 160839, stat = "versatility" },  -- Ironpeel Plantain
        { id = 122346, buff = 180746, stat = "versatility" },  -- Jumbo Sea Dog
        { id = 118270, buff = 160726, stat = "haste" },  -- O'ruk Orange
        { id = 118274, buff = 174077, stat = "mastery" },  -- Perfect Fuzzy Pear
        { id = 118276, buff = 174080, stat = "crit" },  -- Perfect Greenskin Apple
        { id = 118277, buff = 174078, stat = "versatility" },  -- Perfect Ironpeel Plantain
        { id = 118275, buff = 174062, stat = "crit" },  -- Perfect Nagrand Cherry
        { id = 118273, buff = 174079, stat = "haste" },  -- Perfect O'ruk Orange
        { id = 122345, buff = 180745, stat = "crit" },  -- Pickled Eel
        { id = 120168, buff = 177931, stat = "versatility" },  -- Pre-Mixed Pot of Noodles
        { id = 111443, buff = 160778, stat = "versatility" },  -- Salted Skulker
        { id = 122344, buff = 180749, stat = "crit" },  -- Salty Squid Roll
        { id = 111452, buff = 160897, stat = "mastery" },  -- Sleeper Surprise
        { id = 122343, buff = 180750, stat = "mastery" },  -- Sleeper Sushi
        { id = 114982, buff = 169356 },  -- Song Flower
        { id = 114238, buff = 168349, stat = "versatility" },  -- Spiced Barbed Trout
        { id = 111451, buff = 160895, stat = "versatility" },  -- Starflower Sandwich
        { id = 111447, buff = 160883, stat = "stamina" },  -- Talador Surf and Turf
        { id = 122347, buff = 180747, stat = "stamina" },  -- Whiptail Fillet
        { id = 104340, buff = 124220 },  -- Crazy Snake Noodles
        { id = 98127, buff = 124219, stat = "mastery" },  -- Dented Can of Kaja'Cola
        { id = 101747, buff = 146807, stat = "versatility" },  -- Farmer's Delight
        { id = 101750, buff = 146804, stat = "strength" },  -- Fluffy Silkfeather Omelet
        { id = 104343, buff = 124216, stat = "haste" },  -- Golden Dragon Noodles
        { id = 94535, buff = 124219, stat = "mastery" },  -- Grilled Dinosaur Haunch
        { id = 79320, buff = 111840, stat = "stamina" },  -- Half a Lovely Apple
        { id = 104339, buff = 125071 },  -- Harmonious River Noodles
        { id = 105721, buff = 124219, stat = "mastery" },  -- Hot Papaya Milk
        { id = 104344, buff = 124218, stat = "crit" },  -- Lucky Mushroom Noodles
        { id = 101745, buff = 146809, stat = "mastery" },  -- Mango Ice
        { id = 81414, buff = 124219, stat = "mastery" },  -- Pearl Milk Tea
        { id = 101746, buff = 146805, stat = "agility" },  -- Seasoned Pomfruit Slices
        { id = 101748, buff = 146806, stat = "intellect" },  -- Spiced Blossom Soup
        { id = 104342, buff = 124218, stat = "crit" },  -- Spicy Mushan Noodles
        { id = 86073, buff = 125113 },  -- Spicy Salmon
        { id = 86074, buff = 125115, stat = "haste" },  -- Spicy Vegetable Chips
        { id = 104341, buff = 124217, stat = "haste" },  -- Steaming Goat Noodles
        { id = 101749, buff = 146808, stat = "stamina" },  -- Stuffed Lushrooms
        { id = 81406, buff = 124213, stat = "mastery" },  -- Roasted Barley Tea
        { id = 86070, buff = 125106, stat = "crit" },  -- Wildfowl Ginseng Soup
        { id = 103647, buff = 127770, stat = "haste" },  -- Chronambulatrix
        { id = 70924, buff = 100368, stat = "intellect" },  -- Eternal Eye of Elune
        { id = 70925, buff = 100373, stat = "agility" },  -- Eternal Lunar Pear
        { id = 70926, buff = 100375, stat = "versatility" },  -- Eternal Moonberry
        { id = 70927, buff = 100377, stat = "strength" },  -- Eternal Sunfruit
        { id = 88382, buff = 127770, stat = "haste" },  -- Keenbean Kafa
        { id = 90457, buff = 131828, stat = "mastery" },  -- Mah's Warm Yak-Tail Stew
        { id = 103646, buff = 127770, stat = "haste" },  -- Rejuvenating Potion
        { id = 103645, buff = 127770, stat = "haste" },  -- Scroll of the Mystics
        { id = 89594, buff = 130356, stat = "intellect" },  -- Serpent Brew of Serenity
        { id = 89601, buff = 130348, stat = "agility" },  -- Tiger Brew of Serenity
        { id = 62661, buff = 87551, stat = "crit" },  -- Baked Rockfish
        { id = 62665, buff = 87552, stat = "haste" },  -- Basilisk Liverdog
        { id = 62670, buff = 87545, stat = "strength" },  -- Beer-Basted Crocolisk
        { id = 62668, buff = 87555 },  -- Blackbelly Sushi
        { id = 62655, buff = 87563, stat = "haste" },  -- Broiled Mountain Trout
        { id = 62664, buff = 87635, stat = "haste" },  -- Crocolisk Au Gratin
        { id = 62666, buff = 87548, stat = "versatility" },  -- Delicious Sagefish Tail
        { id = 62662, buff = 87550, stat = "crit" },  -- Grilled Dragon
        { id = 62659, buff = 87556, stat = "strength" },  -- Hearty Seafood Soup
        { id = 62663, buff = 87549, stat = "mastery" },  -- Lavascale Minestrone
        { id = 62651, buff = 87562, stat = "crit" },  -- Lightly Fried Lurker
        { id = 62657, buff = 87564 },  -- Lurker Lunch
        { id = 62667, buff = 87554 },  -- Mushroom Sauce Mudfish
        { id = 62660, buff = 87558, stat = "intellect" },  -- Pickled Guppy
        { id = 62653, buff = 87560, stat = "mastery" },  -- Salted Eye
        { id = 62652, buff = 87561, stat = "haste" },  -- Seasoned Crab
        { id = 89593, buff = 130355, stat = "intellect" },  -- Serpent Brew of Fallen Blossoms
        { id = 62671, buff = 87547, stat = "intellect" },  -- Severed Sagefish Head
        { id = 62669, buff = 87546, stat = "agility" },  -- Skewered Eel
        { id = 62658, buff = 87557, stat = "agility" },  -- Tender Baked Turtle
        { id = 89600, buff = 130347, stat = "agility" },  -- Tiger Brew of Fallen Blossoms
        { id = 62656, buff = 87559, stat = "versatility" },  -- Whitecrest Gumbo
        { id = 89592, buff = 130354, stat = "intellect" },  -- Serpent Brew of Meditation
        { id = 42779, buff = 53284, stat = "stamina" },  -- Steaming Chicken Soup
        { id = 89599, buff = 130346, stat = "agility" },  -- Tiger Brew of Meditation
        { id = 42942, buff = 57102, stat = "haste" },  -- Baked Manta Ray
        { id = 42999, buff = 57367, stat = "agility" },  -- Blackened Dragonfin
        { id = 42998, buff = 57365, stat = "versatility" },  -- Cuttlesteak
        { id = 43268, buff = 57294 },  -- Dalaran Clam Chowder
        { id = 43000, buff = 57371, stat = "strength" },  -- Dragonfin Filet
        { id = 34767, buff = 57327, stat = "stamina" },  -- Firecracker Salmon
        { id = 34762, buff = 57079 },  -- Grilled Sculpin
        { id = 42995, buff = 57358, stat = "crit" },  -- Hearty Rhino
        { id = 34769, buff = 57332, stat = "haste" },  -- Imperial Manta Steak
        { id = 34748, buff = 57111 },  -- Mammoth Meal
        { id = 34754, buff = 57325 },  -- Mega Mammoth Meal
        { id = 34758, buff = 57334, stat = "versatility" },  -- Mighty Rhino Dogs
        { id = 34765, buff = 57107, stat = "versatility" },  -- Pickled Fangtooth
        { id = 34764, buff = 57100, stat = "crit" },  -- Poached Nettlefish
        { id = 34766, buff = 57325 },  -- Poached Northern Sculpin
        { id = 34752, buff = 57291, stat = "versatility" },  -- Rhino Dogs
        { id = 42994, buff = 57356, stat = "haste" },  -- Rhinolicious Wormsteak
        { id = 34751, buff = 57288, stat = "haste" },  -- Roasted Worg
        { id = 34125, buff = 57288, stat = "haste" },  -- Shoveltusk Soup
        { id = 34749, buff = 57139, stat = "stamina" },  -- Shoveltusk Steak
        { id = 34763, buff = 57097, stat = "stamina" },  -- Smoked Salmon
        { id = 42996, buff = 57360, stat = "haste" },  -- Snapper Extreme
        { id = 34756, buff = 57329, stat = "crit" },  -- Spiced Worm Burger
        { id = 34768, buff = 57329, stat = "crit" },  -- Spicy Blue Nettlefish
        { id = 42993, buff = 57334, stat = "versatility" },  -- Spicy Fried Herring
        { id = 39691, buff = 57286, stat = "crit" },  -- Succulent Orca Stew
        { id = 34755, buff = 57327, stat = "stamina" },  -- Tender Shoveltusk Steak
        { id = 34757, buff = 57332, stat = "haste" },  -- Very Burnt Worg
        { id = 44953, buff = 57360, stat = "haste" },  -- Worg Tartare
        { id = 34750, buff = 57286, stat = "crit" },  -- Worm Delight
        { id = 33052, buff = 33257, stat = "stamina" },  -- Fisherman's Feast
        { id = 30358, buff = 33261, stat = "agility" },  -- Oronok's Tuber of Agility
        { id = 30357, buff = 33268, stat = "versatility" },  -- Oronok's Tuber of Healing
        { id = 30361, buff = 33263, stat = "versatility" },  -- Oronok's Tuber of Spell Power
        { id = 30359, buff = 33256, stat = "strength" },  -- Oronok's Tuber of Strength
        { id = 89591, buff = 130353, stat = "intellect" },  -- Serpent Brew of Pilgrimage
        { id = 33825, buff = 43722, stat = "crit" },  -- Skullfish Soup
        { id = 33872, buff = 43764, stat = "haste" },  -- Spicy Hot Talbuk
        { id = 89598, buff = 130345, stat = "agility" },  -- Tiger Brew of Pilgrimage
        { id = 27657, buff = 33263, stat = "versatility" },  -- Blackened Basilisk
        { id = 27663, buff = 33265, stat = "stamina" },  -- Blackened Sporefish
        { id = 33867, buff = 33254, stat = "stamina" },  -- Broiled Bloodfin
        { id = 27651, buff = 33254, stat = "stamina" },  -- Buzzard Bites
        { id = 30155, buff = 33254, stat = "stamina" },  -- Clam Bar
        { id = 31673, buff = 33263, stat = "versatility" },  -- Crunchy Serpent
        { id = 21023, buff = 25661, stat = "stamina" },  -- Dirge's Kickin' Chimaerok Chops
        { id = 24009, buff = 145635, stat = "stamina" },  -- Dried Fruit Rations
        { id = 24008, buff = 145635, stat = "stamina" },  -- Dried Mushroom Rations
        { id = 27662, buff = 33254, stat = "stamina" },  -- Feltail Delight
        { id = 27666, buff = 33268, stat = "versatility" },  -- Golden Fish Sticks
        { id = 27664, buff = 33261, stat = "agility" },  -- Grilled Mudfish
        { id = 29292, buff = 24799, stat = "strength" },  -- Helboar Bacon
        { id = 140342, buff = 35272, stat = "stamina" },  -- Lean - Mok'Nathal Shortribs
        { id = 24539, buff = 18193, stat = "versatility" },  -- Marsh Lichen
        { id = 31672, buff = 35272, stat = "stamina" },  -- Mok'Nathal Shortribs
        { id = 27665, buff = 33263, stat = "versatility" },  -- Poached Bluefish
        { id = 27655, buff = 33259 },  -- Ravager Dog
        { id = 28501, buff = 145635, stat = "stamina" },  -- Ravager Egg Omelet
        { id = 27658, buff = 33256, stat = "strength" },  -- Roasted Clefthoof
        { id = 89590, buff = 130352, stat = "intellect" },  -- Serpent Brew of Adversity
        { id = 32721, buff = 42293, stat = "stamina" },  -- Skyguard Rations
        { id = 27667, buff = 33257, stat = "stamina" },  -- Spicy Crawdad
        { id = 27660, buff = 35272, stat = "stamina" },  -- Talbuk Steak
        { id = 89597, buff = 130344, stat = "agility" },  -- Tiger Brew of Adversity
        { id = 27659, buff = 33261, stat = "agility" },  -- Warp Burger
        { id = 13810, buff = 18125, stat = "strength" },  -- Blessed Sunfruit
        { id = 35563, buff = 46899 },  -- Charred Bear Kabobs
        { id = 89589, buff = 130351, stat = "intellect" },  -- Initiate's Serpent Brew
        { id = 89596, buff = 130343, stat = "agility" },  -- Initiate's Tiger Brew
        { id = 35565, buff = 46687, stat = "intellect" },  -- Juicy Bear Burger
        { id = 13934, buff = 145635, stat = "stamina" },  -- Mightfish Steak
        { id = 18254, buff = 22730, stat = "intellect" },  -- Runn Tum Tuber Surprise
        { id = 20452, buff = 24799, stat = "strength" },  -- Smoked Desert Dumplings
        { id = 16971, buff = 19710, stat = "stamina" },  -- Clamlette Surprise
        { id = 12218, buff = 19710, stat = "stamina" },  -- Monster Omelet
        { id = 12216, buff = 19710, stat = "stamina" },  -- Spiced Chili Crab
        { id = 18045, buff = 19710, stat = "stamina" },  -- Tender Wolf Steak
        { id = 33004, buff = 64057 },  -- Clamlette Magnifique
        { id = 13927, buff = 18191, stat = "stamina" },  -- Cooked Glossy Mightfish
        { id = 13928, buff = 18192, stat = "agility" },  -- Grilled Squid
        { id = 12215, buff = 19710, stat = "stamina" },  -- Heavy Kodo Stew
        { id = 13929, buff = 19709, stat = "stamina" },  -- Hot Smoked Bass
        { id = 89588, buff = 130350, stat = "intellect" },  -- Novice's Serpent Brew
        { id = 89595, buff = 130342, stat = "agility" },  -- Novice's Tiger Brew
        { id = 17222, buff = 19710, stat = "stamina" },  -- Spider Sausage
        { id = 57519, buff = 19705, stat = "stamina" },  -- Cookie's Special Ramlette
        { id = 4457, buff = 19709, stat = "stamina" },  -- Barbecued Buzzard Wing
        { id = 12213, buff = 19709, stat = "stamina" },  -- Carrion Surprise
        { id = 6038, buff = 19709, stat = "stamina" },  -- Giant Clam Scorcho
        { id = 20074, buff = 19709, stat = "stamina" },  -- Heavy Crocolisk Stew
        { id = 13851, buff = 19709, stat = "stamina" },  -- Hot Wolf Ribs
        { id = 12212, buff = 19709, stat = "stamina" },  -- Jungle Stew
        { id = 12214, buff = 19709, stat = "stamina" },  -- Mystery Stew
        { id = 12210, buff = 19709, stat = "stamina" },  -- Roast Raptor
        { id = 3729, buff = 19709, stat = "stamina" },  -- Soothing Turtle Bisque
        { id = 3728, buff = 19709, stat = "stamina" },  -- Tasty Lion Steak
        { id = 5342, buff = 6114, stat = "intellect" },  -- Raptor Punch
        { id = 3726, buff = 19708, stat = "stamina" },  -- Big Bear Steak
        { id = 5479, buff = 19708, stat = "stamina" },  -- Crispy Lizard Tail
        { id = 3664, buff = 19708, stat = "stamina" },  -- Crocolisk Gumbo
        { id = 3665, buff = 19708, stat = "stamina" },  -- Curiously Tasty Omelet
        { id = 5527, buff = 19708, stat = "stamina" },  -- Goblin Deviled Clams
        { id = 3666, buff = 19708, stat = "stamina" },  -- Gooey Spider Cake
        { id = 3727, buff = 19708, stat = "stamina" },  -- Hot Lion Chops
        { id = 5480, buff = 19708, stat = "stamina" },  -- Lean Venison
        { id = 12209, buff = 19708, stat = "stamina" },  -- Lean Wolf Steak
        { id = 3663, buff = 19708, stat = "stamina" },  -- Murloc Fin Soup
        { id = 1082, buff = 19708, stat = "stamina" },  -- Redridge Goulash
        { id = 1017, buff = 19708, stat = "stamina" },  -- Seasoned Wolf Kabob
        { id = 27635, buff = 19705, stat = "stamina" },  -- Lynx Steak
        { id = 24105, buff = 19705, stat = "stamina" },  -- Roasted Moongraze Tenderloin
        { id = 27636, buff = 19706, stat = "stamina" },  -- Bat Bites
        { id = 3220, buff = 19706, stat = "stamina" },  -- Blood Sausage
        { id = 5525, buff = 19706, stat = "stamina" },  -- Boiled Clams
        { id = 11584, buff = 19705, stat = "stamina" },  -- Cactus Apple Surprise
        { id = 276611, buff = 19706, stat = "stamina" },  -- Clam Stuffed Crab
        { id = 2684, buff = 19706, stat = "stamina" },  -- Coyote Steak
        { id = 2683, buff = 19706, stat = "stamina" },  -- Crab Cake
        { id = 3662, buff = 19706, stat = "stamina" },  -- Crocolisk Steak
        { id = 22645, buff = 19706, stat = "stamina" },  -- Crunchy Spider Surprise
        { id = 2687, buff = 19706, stat = "stamina" },  -- Dry Pork Ribs
        { id = 5476, buff = 19706, stat = "stamina" },  -- Fillet of Frenzy
        { id = 724, buff = 19706, stat = "stamina" },  -- Goretusk Liver Pie
        { id = 140338, buff = 19706, stat = "stamina" },  -- Mana-Wrapped Goretusk Liver Pie
        { id = 5477, buff = 19706, stat = "stamina" },  -- Strider Stew
        { id = 2888, buff = 19705, stat = "stamina" },  -- Beer Basted Boar Ribs
        { id = 23756, buff = 19705, stat = "stamina" },  -- Cookie's Jumbo Gumbo
        { id = 12224, buff = 19705, stat = "stamina" },  -- Crispy Bat Wing
        { id = 184682, buff = 347173, stat = "versatility" },  -- Extra Lemony Herb Filet
        { id = 6888, buff = 19705, stat = "stamina" },  -- Herb Baked Egg
        { id = 5472, buff = 19705, stat = "stamina" },  -- Kaldorei Spider Kabob
        { id = 126934, buff = 185736, stat = "versatility" },  -- Lemon Herb Filet
        { id = 5474, buff = 19705, stat = "stamina" },  -- Roasted Kodo Meat
        { id = 77264, buff = 108028, stat = "intellect" },  -- Small Bamboo Shoot
        { id = 77273, buff = 108031, stat = "strength" },  -- Small Rice Cake
        { id = 77272, buff = 108032, stat = "agility" },  -- Small Sugarcane Stalk
        { id = 2680, buff = 19705, stat = "stamina" },  -- Spiced Wolf Meat
        -- exp -3
        { id = 210821, buff = 19711, stat = "stamina" },  -- Berry Chocolate Tart
        { id = 210819, buff = 19710, stat = "stamina" },  -- Chocolate-Covered Cherries
        { id = 34411, buff = 45245, stat = "stamina" },  -- Hot Apple Cider
        { id = 21254, buff = 110645, stat = "primary" },  -- Winter Veil Cookie
        { id = 210842, buff = 226807, stat = "versatility" },  -- Fresh Fig
        { id = 210841, buff = 226805, stat = "mastery" },  -- Buttered Oysters
        { id = 44839, buff = 65410, stat = "haste" },  -- Candied Sweet Potato
        { id = 7807, buff = 19705, stat = "stamina" },  -- Candy Bar
        { id = 7808, buff = 19705, stat = "stamina" },  -- Chocolate Square
        { id = 116405, buff = 65412, stat = "stamina" },  -- Congealed Cranberry Chutney
        { id = 44840, buff = 226807, stat = "versatility" },  -- Cranberry Chutney
        { id = 17197, buff = 19705, stat = "stamina" },  -- Gingerbread Cookie
        { id = 116409, buff = 175785, stat = "crit" },  -- Gourmet Pumpkin Pie
        { id = 116408, buff = 175784, stat = "stamina" },  -- Herb-Infused Stuffing
        { id = 7806, buff = 19705, stat = "stamina" },  -- Lollipop
        { id = 44836, buff = 175785, stat = "crit" },  -- Pumpkin Pie
        { id = 44838, buff = 226805, stat = "mastery" },  -- Slow-Roasted Turkey
        { id = 116407, buff = 65414 },  -- Slow-Smoked Turkey
        { id = 44837, buff = 175784, stat = "stamina" },  -- Spice Bread Stuffing
        { id = 116406, buff = 65410, stat = "haste" },  -- Twice-Baked Sweet Potato
        { id = 17198, buff = 19705, stat = "stamina" },  -- Winter Veil Eggnog
    },
    augmentRune = {
        -- Midnight / current
        { id = 259085, buff = 1264426, stat = "primary" },  -- Void-Touched Augment Rune
        -- Dragonflight / TWW
        { id = 224572, buff = 453250, stat = "primary" },  -- Crystallized Augment Rune
        { id = 243191, buff = 1234969, stat = "primary" },  -- Ethereal Augment Rune
        { id = 246492, buff = 1242347, stat = "primary" },  -- Soulgorged Augment Rune
        -- Shadowlands
        { id = 201325, buff = 393438, stat = "agility" },  -- Draconic Augment Rune
        { id = 211495, buff = 393438, stat = "agility" },  -- Dreambound Augment Rune
        -- Battle for Azeroth
        { id = 181468, buff = 347901, stat = "agility" },  -- Veiled Augment Rune
        -- Legion
        { id = 190384, buff = 367405, stat = "agility" },  -- Eternal Augment Rune
        { id = 160053, buff = 270058, stat = "agility" },  -- Battle-Scarred Augment Rune
        { id = 174906, buff = 317065, stat = "agility" },  -- Lightning-Forged Augment Rune
        -- Warlords of Draenor
        { id = 153023, buff = 284307, stat = "agility" },  -- Lightforged Augment Rune
        -- Classic
        { id = 140587, buff = 224001, stat = "agility" },  -- Defiled Augment Rune
        { id = 118632, buff = 175457, stat = "intellect" },  -- Focus Augment Rune
        { id = 118630, buff = 175456, stat = "agility" },  -- Hyper Augment Rune
        { id = 118631, buff = 175439, stat = "strength" },  -- Stout Augment Rune
    },
    weaponEnchant = {
        -- Midnight / current
        { id = 243736, buff = 1237001 },  -- Oil of Dawn
        { id = 237369, buff = 1224333 },  -- Refulgent Weightstone
        { id = 237371, buff = 1224328 },  -- Refulgent Whetstone
        { id = 243734, buff = 1237006 },  -- Thalassian Phoenix Oil
        { id = 243735, buff = 1237002 },  -- Oil of Dawn
        { id = 237367, buff = 1224332 },  -- Refulgent Weightstone
        { id = 237370, buff = 1224331 },  -- Refulgent Whetstone
        { id = 243733, buff = 1237008 },  -- Thalassian Phoenix Oil
        -- Dragonflight / TWW
        { id = 220156, buff = 444755 },  -- Bubbling Wax
        { id = 222510, buff = 458937 },  -- Ironclaw Weightstone
        { id = 222504, buff = 458934 },  -- Ironclaw Whetstone
        { id = 222509, buff = 458936 },  -- Ironclaw Weightstone
        { id = 222503, buff = 458933 },  -- Ironclaw Whetstone
        { id = 222508, buff = 458935 },  -- Ironclaw Weightstone
        { id = 222502, buff = 458932 },  -- Ironclaw Whetstone
        { id = 224105, buff = 451869 },  -- Algari Mana Oil
        { id = 224106, buff = 451873 },  -- Algari Mana Oil
        { id = 224107, buff = 451874 },  -- Algari Mana Oil
        { id = 224108, buff = 451926 },  -- Oil of Beledar's Grace
        { id = 224109, buff = 451925 },  -- Oil of Beledar's Grace
        { id = 224110, buff = 451927 },  -- Oil of Beledar's Grace
        { id = 224111, buff = 451882 },  -- Oil of Deep Toxins
        { id = 224112, buff = 451901 },  -- Oil of Deep Toxins
        { id = 224113, buff = 451902 },  -- Oil of Deep Toxins
        { id = 234382, buff = 1213839 },  -- Ensemble: Unkindled Waxweave Panoply
        { id = 226224, buff = 458517 },  -- Luminous Nerubian Catalyst Stone
        -- Shadowlands
        { id = 191944, buff = 371677 },  -- Primal Weightstone
        { id = 191940, buff = 396157 },  -- Primal Whetstone
        { id = 191945, buff = 371678 },  -- Primal Weightstone
        { id = 191933, buff = 396155 },  -- Primal Whetstone
        { id = 191943, buff = 371676 },  -- Primal Weightstone
        { id = 191939, buff = 396156 },  -- Primal Whetstone
        -- Battle for Azeroth
        { id = 171436, buff = 322749 },  -- Porous Sharpening Stone
        { id = 171438, buff = 322761 },  -- Porous Weightstone
        { id = 171437, buff = 322762 },  -- Shaded Sharpening Stone
        { id = 171439, buff = 322763 },  -- Shaded Weightstone
        { id = 180683, buff = 334428 },  -- Guardian Stonewing
        { id = 180684, buff = 334431 },  -- Sentinel Stonewing
        { id = 181337, buff = 336160 },  -- Stonefiend's Wings
        { id = 176139, buff = 321651 },  -- Contract: Stoneborn Reserves
        { id = 186981, buff = 355159 },  -- Porous Stone Statue
        { id = 178686, buff = 327299 },  -- RSVP: Stonehead
        { id = 186982, buff = 355175 },  -- Shaded Stone Statue
        { id = 181771, buff = 343719 },  -- Stonehead's Best Bud Bracelet
        { id = 189572, buff = 365941 },  -- Tame Prime: Hadeon the Stonebreaker
        -- Legion
        { id = 165719, buff = 285840 },  -- Monelite Whetstone
        { id = 165720, buff = 285840 },  -- Monelite Whetstone
        { id = 162120, buff = 276228 },  -- Platinum Whetstone
        { id = 165748, buff = 276228 },  -- Platinum Whetstone
        { id = 167077, buff = 300539 },  -- Scrying Stone
        { id = 161385, buff = 275199 },  -- Stonefist Watch
        { id = 162511, buff = 276927 },  -- Stonetusk Watch
        -- Warlords of Draenor
        { id = 147303, buff = 240515 },  -- Giant Elemental's Closed Stone Fist
        { id = 152927, buff = 253837 },  -- Serrated Stone Axe
        { id = 131746, buff = 208705 },  -- Stonehide Leather Barding
        -- Mists of Pandaria
        { id = 118221, buff = 173893 },  -- Petrification Stone
        -- Cataclysm
        { id = 87872, buff = 127563 },  -- Desecrated Oil
        -- Classic
        { id = 23529, buff = 29453 },  -- Adamantite Sharpening Stone
        { id = 28421, buff = 34340 },  -- Adamantite Weightstone
        { id = 22522, buff = 28017 },  -- Superior Wizard Oil
        { id = 23528, buff = 29452 },  -- Fel Sharpening Stone
        { id = 28420, buff = 34339 },  -- Fel Weightstone
        { id = 25884, buff = 32806 },  -- Primal Stone Statue
        { id = 22521, buff = 28013 },  -- Superior Mana Oil
        { id = 29796, buff = 35745 },  -- Socrethar's Teleportation Stone
        -- Classic
        { id = 140329, buff = 224382 },  -- Infinite Stone
        { id = 146919, buff = 240307 },  -- Portal-Stone: An'thyna
        { id = 146920, buff = 240310 },  -- Portal-Stone: Fel Obliterator
        { id = 146918, buff = 240304 },  -- Portal-Stone: Force-Commander Xillious
        { id = 146921, buff = 240313 },  -- Portal-Stone: Illisthyndria
        { id = 146917, buff = 240301 },  -- Portal-Stone: Skulguloth
        { id = 146916, buff = 240298 },  -- Portal-Stone: Than'otalion
        { id = 116981, buff = 172376 },  -- Fire Ammonite Oil
        { id = 122457, buff = 181062 },  -- Ultimate Battle-Training Stone
        { id = 133890, buff = 201800 },  -- Stoneshroom
        { id = 116119, buff = 170895 },  -- Ango'rosh Sorcerer Stone
        { id = 62345, buff = 86901 },  -- Greater Inscription of Jagged Stone
        { id = 68716, buff = 86901 },  -- Greater Inscription of Jagged Stone
        { id = 62344, buff = 86900 },  -- Lesser Inscription of Jagged Stone
        { id = 89303, buff = 129894 },  -- Stack of Stone Blocks
        { id = 36899, buff = 47904 },  -- Exceptional Mana Oil
        { id = 18262, buff = 22756 },  -- Elemental Sharpening Stone
        { id = 23123, buff = 28898 },  -- Blessed Wizard Oil
        { id = 203862, buff = 25123 },  -- Brilliant Mana Oil
        { id = 203865, buff = 25122 },  -- Brilliant Wizard Oil
        { id = 23122, buff = 28891 },  -- Consecrated Sharpening Stone
        { id = 25883, buff = 32805 },  -- Dense Stone Statue
        { id = 20747, buff = 25120 },  -- Lesser Mana Oil
        { id = 20750, buff = 25121 },  -- Wizard Oil
        { id = 12404, buff = 16138 },  -- Dense Sharpening Stone
        { id = 12643, buff = 16622 },  -- Dense Weightstone
        { id = 8956, buff = 11350 },  -- Oil of Immolation
        { id = 118699, buff = 11350 },  -- Oil of Immolation
        { id = 3829, buff = 3595 },  -- Frost Oil
        { id = 20746, buff = 25119 },  -- Lesser Wizard Oil
        { id = 25882, buff = 32804 },  -- Solid Stone Statue
        { id = 7964, buff = 9900 },  -- Solid Sharpening Stone
        { id = 7965, buff = 9903 },  -- Solid Weightstone
        { id = 3824, buff = 3594 },  -- Shadow Oil
        { id = 25881, buff = 32803 },  -- Heavy Stone Statue
        { id = 20745, buff = 25118 },  -- Minor Mana Oil
        { id = 2871, buff = 2830 },  -- Heavy Sharpening Stone
        { id = 3241, buff = 3114 },  -- Heavy Weightstone
        { id = 25880, buff = 32802 },  -- Coarse Stone Statue
        { id = 1322, buff = 7396, stat = "haste" },  -- Fishliver Oil
        { id = 2863, buff = 2829 },  -- Coarse Sharpening Stone
        { id = 3240, buff = 3113 },  -- Coarse Weightstone
        { id = 20744, buff = 25117 },  -- Minor Wizard Oil
        { id = 6458, buff = 433 },  -- Oil Covered Fish
        { id = 25498, buff = 32254 },  -- Rough Stone Statue
        { id = 1177, buff = 54497 },  -- Oil of Olaf
        { id = 1434, buff = 13424 },  -- Glowing Wax Stick
        { id = 2862, buff = 2828 },  -- Rough Sharpening Stone
        { id = 3239, buff = 3112 },  -- Rough Weightstone
        { id = 116424, buff = 171515 },  -- Aquatic Battle-Training Stone
        { id = 87257, buff = 126589 },  -- Arcane Familiar Stone
        { id = 116374, buff = 162984 },  -- Beast Battle-Training Stone
        { id = 116418, buff = 171520 },  -- Critter Battle-Training Stone
        { id = 147564, buff = 242134 },  -- Diamond Stone
        { id = 116419, buff = 171516 },  -- Dragonkin Battle-Training Stone
        { id = 116420, buff = 171522 },  -- Elemental Battle-Training Stone
        { id = 127755, buff = 187567 },  -- Fel-Touched Battle-Training Stone
        { id = 87258, buff = 126587 },  -- Fiery Familiar Stone
        { id = 92679, buff = 134488 },  -- Flawless Aquatic Battle-Stone
        { id = 92741, buff = 134644 },  -- Flawless Battle-Stone
        { id = 116429, buff = 171525 },  -- Flawless Battle-Training Stone
        { id = 92675, buff = 134482 },  -- Flawless Beast Battle-Stone
        { id = 92676, buff = 134484 },  -- Flawless Critter Battle-Stone
        { id = 92683, buff = 134492 },  -- Flawless Dragonkin Battle-Stone
        { id = 92665, buff = 134448 },  -- Flawless Elemental Battle-Stone
        { id = 92677, buff = 134486 },  -- Flawless Flying Battle-Stone
        { id = 92682, buff = 134491 },  -- Flawless Humanoid Battle-Stone
        { id = 92678, buff = 134487 },  -- Flawless Magic Battle-Stone
        { id = 92680, buff = 134489 },  -- Flawless Mechanical Battle-Stone
        { id = 92681, buff = 134490 },  -- Flawless Undead Battle-Stone
        { id = 116421, buff = 171518 },  -- Flying Battle-Training Stone
        { id = 8095, buff = 10723 },  -- Hinott's Oil
        { id = 116416, buff = 171517 },  -- Humanoid Battle-Training Stone
        { id = 87259, buff = 126586 },  -- Icy Familiar Stone
        { id = 137391, buff = 212863 },  -- Immaculate Aquatic Battle-Stone
        { id = 137627, buff = 213521 },  -- Immaculate Battle-Stone
        { id = 137394, buff = 212862 },  -- Immaculate Beast Battle-Stone
        { id = 137393, buff = 212856 },  -- Immaculate Critter Battle-Stone
        { id = 137387, buff = 212859 },  -- Immaculate Dragonkin Battle-Stone
        { id = 137395, buff = 212857 },  -- Immaculate Elemental Battle-Stone
        { id = 137396, buff = 212860 },  -- Immaculate Flying Battle-Stone
        { id = 137388, buff = 212866 },  -- Immaculate Humanoid Battle-Stone
        { id = 137392, buff = 212858 },  -- Immaculate Magic Battle-Stone
        { id = 137390, buff = 212861 },  -- Immaculate Mechanical Battle-Stone
        { id = 137389, buff = 212864 },  -- Immaculate Undead Battle-Stone
        { id = 142359, buff = 230286 },  -- Lava Oil
        { id = 116422, buff = 171521 },  -- Magic Battle-Training Stone
        { id = 98715, buff = 134644 },  -- Marked Flawless Battle-Stone
        { id = 116417, buff = 171523 },  -- Mechanical Battle-Training Stone
        { id = 92689, buff = 134499 },  -- Polished Aquatic Battle-Stone
        { id = 92742, buff = 134496 },  -- Polished Battle-Stone
        { id = 92685, buff = 134495 },  -- Polished Beast Battle-Stone
        { id = 92686, buff = 134761 },  -- Polished Critter Battle-Stone
        { id = 92693, buff = 134504 },  -- Polished Dragonkin Battle-Stone
        { id = 92684, buff = 134494 },  -- Polished Elemental Battle-Stone
        { id = 92687, buff = 134497 },  -- Polished Flying Battle-Stone
        { id = 92692, buff = 134503 },  -- Polished Humanoid Battle-Stone
        { id = 92688, buff = 134498 },  -- Polished Magic Battle-Stone
        { id = 92690, buff = 134501 },  -- Polished Mechanical Battle-Stone
        { id = 92691, buff = 134502 },  -- Polished Undead Battle-Stone
        { id = 219146, buff = 442935 },  -- Set Keystone Map: Stonevault
        { id = 147563, buff = 242133 },  -- Stone Totem
        { id = 30309, buff = 11009 },  -- Stonebreaker Brew
        { id = 116423, buff = 171519 },  -- Undead Battle-Training Stone
        { id = 139816, buff = 221923 },  -- Well-Worn Stone
        -- exp -3
        { id = 223647, buff = 449639 },  -- Lifeless Stone Ring
    },
})

-- ──────────────────────────── HAND-CURATED (not generated) ────────────────────────────
-- Toys and class self-buffs flow through the same detect+overlay pipeline via `source`.
-- Add them with SpellDB.RegisterPrecombatBuffsExtra so a regen never clobbers them.
if SpellDB.RegisterPrecombatBuffsExtra then
    SpellDB.RegisterPrecombatBuffsExtra({
        -- Speed (movement): long well-fed FOODS only (>= 20m buff) - a maintained pre-buff,
        -- not a 15s potion burst (useless as an OOC reminder). Off by default.
        { category = "speed", id = 212492, buff = 454497 },   -- Twilight-Spiced Grouper (60m)
        { category = "speed", id = 223971, buff = 456578 },   -- Azj-Kahet Special (20m)
        { category = "speed", id = 98116,  buff = 142280 },   -- Freeze-Dried Hyena Jerky (60m)

        -- XP (leveling): long XP buffs only (>= 20m). Off by default. Tome of Combat Training
        -- (10m) intentionally excluded by the duration floor.
        { category = "xp", id = 166750, buff = 289982 },      -- Draught of Ten Lands (60m)
        { category = "xp", id = 166751, buff = 289982 },      -- Draught of Ten Lands (60m)
        { category = "xp", id = 239142, buff = 1221184 },     -- Bottle of Mysterious Wisdom (120m)
        { category = "xp", id = 254693, buff = 1258529 },     -- Distilled Knowledge of Timeways (120m)
        { category = "xp", id = 209997, buff = 423860 },      -- Distilled Knowledge of Timeways (120m)

        -- XP / leveling toys (source = "toy": owned via PlayerHasToy, used via /usetoy)
        -- { category = "xp", id = <toyItemID>, buff = <auraSpellID>, source = "toy" },

        -- Class self-buffs (source = "spell": known via IsSpellKnown, cast via type=spell)
        -- { category = "classBuff", id = <spellID>, buff = <auraSpellID>, source = "spell" },
    })
end
