-- SPDX-License-Identifier: GPL-3.0-or-later
-- Copyright (C) 2024-2026 wealdly
--
-- JustAC: imported action-priority lists (per spec, per context) with per-entry
-- gates. GENERATED by tools/gen_simc_rotations.py - do not edit by hand.
--
-- Orderings and conditions derive from SimulationCraft (GPL-3.0,
-- https://github.com/simulationcraft/simc); the pinned source APLs live in
-- tools/simc-apl/ as the corresponding source. Each entry keeps the SECRET-SAFE
-- gates JustAC can evaluate in 12.0 combat (cd / dot / proc-or-buff-window /
-- execute). `delegated` marks a step whose SimC condition also needs a value we
-- cannot read (resources, aura duration/stacks), so it falls back to priority
-- order and Blizzard's live pick. Used to REFINE the AC fixed queue, not replace it.

local RotationImport = LibStub("JustAC-RotationImport", true)
if not RotationImport or not RotationImport.RegisterGated then return end

RotationImport.RegisterGated({
  ["DEATHKNIGHT_1"] = {
    st = {
      {id=55233,gates={{t="buff",id=55233,neg=true}}},  -- vampiric_blood
      {id=46585,gates={}},  -- raise_dead
      {id=49998,gates={{t="buff",id=391477}},delegated=true},  -- death_strike
      {id=49028,gates={}},  -- dancing_rune_weapon
      {id=343294,gates={},delegated=true},  -- soul_reaper
      {id=439843,gates={}},  -- reapers_mark
      {id=50842,gates={{t="buff",id=49028}},delegated=true},  -- blood_boil
      {id=43265,gates={{t="buff",id=43265,neg=true}}},  -- death_and_decay
      {id=195182,gates={},delegated=true},  -- marrowrend
      {id=1263824,gates={}},  -- consumption
      {id=206930,gates={},delegated=true},  -- heart_strike
      {id=195292,gates={},delegated=true},  -- deaths_caress
    },
  },
  ["DEATHKNIGHT_2"] = {
    st = {
      {id=47528,gates={},delegated=true},  -- mind_freeze
      {id=196770,gates={},delegated=true},  -- remorseless_winter
      {id=279302,gates={},delegated=true},  -- frostwyrms_fury
      {id=51271,gates={},delegated=true},  -- pillar_of_frost
      {id=1249658,gates={{t="buff",id=1249658,neg=true}},delegated=true},  -- breath_of_sindragosa
      {id=439843,gates={},delegated=true},  -- reapers_mark
      {id=46585,gates={}},  -- raise_dead
      {id=343294,gates={{t="buff",id=51128}},delegated=true},  -- soul_reaper
      {id=47568,gates={},delegated=true},  -- empower_rune_weapon
      {id=49020,gates={},delegated=true},  -- obliterate
      {id=49184,gates={{t="buff",id=59057}}},  -- howling_blast
      {id=49143,gates={},delegated=true},  -- frost_strike
    },
    aoe = {
      {id=47528,gates={},delegated=true},  -- mind_freeze
      {id=196770,gates={},delegated=true},  -- remorseless_winter
      {id=279302,gates={},delegated=true},  -- frostwyrms_fury
      {id=51271,gates={},delegated=true},  -- pillar_of_frost
      {id=1249658,gates={{t="buff",id=1249658,neg=true}},delegated=true},  -- breath_of_sindragosa
      {id=439843,gates={},delegated=true},  -- reapers_mark
      {id=46585,gates={}},  -- raise_dead
      {id=343294,gates={{t="buff",id=51128}},delegated=true},  -- soul_reaper
      {id=47568,gates={},delegated=true},  -- empower_rune_weapon
      {id=207230,gates={},delegated=true},  -- frostscythe
      {id=49020,gates={},delegated=true},  -- obliterate
      {id=49184,gates={{t="buff",id=59057}},delegated=true},  -- howling_blast
      {id=49143,gates={{t="buff",id=455993}},delegated=true},  -- frost_strike
      {id=194913,gates={},delegated=true},  -- glacial_advance
    },
  },
  ["DEATHKNIGHT_3"] = {
    st = {
      {id=42650,gates={},delegated=true},  -- army_of_the_dead
      {id=1242608,gates={},delegated=true},  -- raise_abomination
      {id=1242147,gates={},delegated=true},  -- summon_gargoyle
      {id=1234559,gates={},delegated=true},  -- desecrate
      {id=325554,gates={},delegated=true},  -- dark_transformation
      {id=220143,gates={},delegated=true},  -- apocalypse
      {id=77575,gates={},delegated=true},  -- outbreak
      {id=55090,gates={{t="buff",id=434143}}},  -- scourge_strike
      {id=47541,gates={{t="buff",id=49530},{t="buff",id=433901,neg=true}},delegated=true},  -- death_coil
      {id=343294,gates={{t="execute"}},delegated=true},  -- soul_reaper
      {id=85948,gates={},delegated=true},  -- festering_strike
    },
    cleave = {
      {id=42650,gates={},delegated=true},  -- army_of_the_dead
      {id=1242608,gates={},delegated=true},  -- raise_abomination
      {id=1242147,gates={},delegated=true},  -- summon_gargoyle
      {id=1234559,gates={},delegated=true},  -- desecrate
      {id=325554,gates={},delegated=true},  -- dark_transformation
      {id=220143,gates={},delegated=true},  -- apocalypse
      {id=77575,gates={{t="dot"}},delegated=true},  -- outbreak
      {id=47541,gates={},delegated=true},  -- death_coil
      {id=55090,gates={{t="buff",id=433901}}},  -- scourge_strike
      {id=85948,gates={{t="buff",id=433901,neg=true}},delegated=true},  -- festering_strike
    },
    aoe = {
      {id=42650,gates={},delegated=true},  -- army_of_the_dead
      {id=1242608,gates={},delegated=true},  -- raise_abomination
      {id=1242147,gates={},delegated=true},  -- summon_gargoyle
      {id=1234559,gates={},delegated=true},  -- desecrate
      {id=325554,gates={},delegated=true},  -- dark_transformation
      {id=220143,gates={},delegated=true},  -- apocalypse
      {id=77575,gates={},delegated=true},  -- outbreak
      {id=85948,gates={{t="buff",id=455397}}},  -- festering_strike
      {id=55090,gates={}},  -- scourge_strike
      {id=47541,gates={},delegated=true},  -- death_coil
      {id=207317,gates={},delegated=true},  -- epidemic
      {id=43265,gates={},delegated=true},  -- death_and_decay
    },
  },
  ["DEMONHUNTER_1"] = {
    st = {
      {id=183752,gates={}},  -- disrupt
      {id=162794,gates={},delegated=true},  -- chaos_strike
      {id=191427,gates={},delegated=true},  -- metamorphosis
      {id=370965,gates={},delegated=true},  -- the_hunt
      {id=390163,gates={{t="cd"}},delegated=true},  -- sigil_of_spite
      {id=198793,gates={{t="buff",id=191427},{t="buff",id=389693,neg=true},{t="cd"}},delegated=true},  -- vengeful_retreat
      {id=232893,gates={{t="buff",id=347461},{t="buff",id=388108}},delegated=true},  -- felblade
      {id=195072,gates={{t="buff",id=347461},{t="buff",id=388108}},delegated=true},  -- fel_rush
      {id=258860,gates={{t="buff",id=191427},{t="cd"}},delegated=true},  -- essence_break
      {id=188499,gates={},delegated=true},  -- blade_dance
      {id=320377,gates={{t="buff",id=191427,neg=true}}},  -- immolation_aura
      {id=198013,gates={{t="buff",id=389693,neg=true}},delegated=true},  -- eye_beam
      {id=162243,gates={}},  -- demons_bite
      {id=1244557,gates={},delegated=true},  -- glaive_tempest
      {id=204596,gates={},delegated=true},  -- sigil_of_flame
      {id=185123,gates={},delegated=true},  -- throw_glaive
      {id=179057,gates={}},  -- chaos_nova
    },
  },
  ["DEMONHUNTER_2"] = {
    st = {
      {id=183752,gates={},delegated=true},  -- disrupt
      {id=189110,gates={}},  -- infernal_strike
      {id=203720,gates={{t="buff",id=203720,neg=true},{t="cd"}}},  -- demon_spikes
      {id=187827,gates={{t="buff",id=187827,neg=true}}},  -- metamorphosis
      {id=320639,gates={},delegated=true},  -- fel_devastation
      {id=228477,gates={},delegated=true},  -- soul_cleave
      {id=203783,gates={},delegated=true},  -- shear
      {id=370965,gates={},delegated=true},  -- the_hunt
      {id=320962,gates={{t="dot",id=320962}}},  -- fiery_brand
      {id=207407,gates={},delegated=true},  -- soul_carver
      {id=390163,gates={}},  -- sigil_of_spite
      {id=320378,gates={}},  -- immolation_aura
      {id=204596,gates={}},  -- sigil_of_flame
      {id=247454,gates={},delegated=true},  -- spirit_bomb
      {id=232893,gates={}},  -- felblade
      {id=198793,gates={}},  -- vengeful_retreat
      {id=204157,gates={}},  -- throw_glaive
    },
  },
  ["DRUID_1"] = {
    st = {
      {id=190984,gates={},delegated=true},  -- wrath
      {id=194153,gates={},delegated=true},  -- starfire
      {id=326646,gates={{t="dot",id=326646}}},  -- moonfire
      {id=93402,gates={}},  -- sunfire
      {id=202770,gates={},delegated=true},  -- fury_of_elune
      {id=205636,gates={},delegated=true},  -- force_of_nature
      {id=395022,gates={},delegated=true},  -- celestial_alignment
      {id=78674,gates={},delegated=true},  -- starsurge
      {id=191034,gates={},delegated=true},  -- starfall
      {id=391528,gates={},delegated=true},  -- convoke_the_spirits
      {id=274281,gates={},delegated=true},  -- new_moon
      {id=88747,gates={{t="dot"}},delegated=true},  -- wild_mushroom
    },
    aoe = {
      {id=78674,gates={},delegated=true},  -- starsurge
      {id=190984,gates={},delegated=true},  -- wrath
      {id=194153,gates={},delegated=true},  -- starfire
      {id=191034,gates={},delegated=true},  -- starfall
      {id=326646,gates={{t="dot",id=326646}},delegated=true},  -- moonfire
      {id=93402,gates={{t="dot",id=93402}}},  -- sunfire
      {id=205636,gates={{t="cd"}},delegated=true},  -- force_of_nature
      {id=202770,gates={},delegated=true},  -- fury_of_elune
      {id=395022,gates={},delegated=true},  -- celestial_alignment
      {id=391528,gates={},delegated=true},  -- convoke_the_spirits
      {id=274281,gates={}},  -- new_moon
      {id=88747,gates={{t="dot"}},delegated=true},  -- wild_mushroom
    },
  },
  ["DRUID_2"] = {
    st = {
      {id=1822,gates={},delegated=true},  -- rake
      {id=5217,gates={},delegated=true},  -- tigers_fury
      {id=391888,gates={},delegated=true},  -- adaptive_swarm
      {id=22568,gates={{t="buff",id=391881}},delegated=true},  -- ferocious_bite
      {id=102543,gates={{t="buff",id=5217}},delegated=true},  -- incarnation
      {id=106951,gates={{t="buff",id=5217}},delegated=true},  -- berserk
      {id=274837,gates={},delegated=true},  -- feral_frenzy
      {id=391528,gates={},delegated=true},  -- convoke_the_spirits
      {id=1079,gates={{t="buff",id=5217},{t="buff",id=106951,neg=true}},delegated=true},  -- rip
      {id=5221,gates={{t="buff",id=106951}},delegated=true},  -- shred
      {id=202028,gates={},delegated=true},  -- brutal_slash
      {id=155625,gates={},delegated=true},  -- moonfire_cat
      {id=106830,gates={{t="dot",id=106830},{t="buff",id=106951,neg=true}}},  -- thrash_cat
      {id=106785,gates={},delegated=true},  -- swipe_cat
      {id=285381,gates={{t="dot",id=285381}},delegated=true},  -- primal_wrath
      {id=8936,gates={{t="buff",id=16974}},delegated=true},  -- regrowth
    },
    aoe = {
      {id=1822,gates={},delegated=true},  -- rake
      {id=5217,gates={},delegated=true},  -- tigers_fury
      {id=391888,gates={},delegated=true},  -- adaptive_swarm
      {id=22568,gates={{t="buff",id=391881}},delegated=true},  -- ferocious_bite
      {id=102543,gates={{t="buff",id=5217}},delegated=true},  -- incarnation
      {id=106951,gates={{t="buff",id=5217}},delegated=true},  -- berserk
      {id=274837,gates={},delegated=true},  -- feral_frenzy
      {id=391528,gates={},delegated=true},  -- convoke_the_spirits
      {id=1079,gates={{t="buff",id=5217},{t="buff",id=106951,neg=true}},delegated=true},  -- rip
      {id=106830,gates={{t="dot",id=106830}},delegated=true},  -- thrash_cat
      {id=202028,gates={{t="buff",id=106951}},delegated=true},  -- brutal_slash
      {id=106785,gates={},delegated=true},  -- swipe_cat
      {id=155625,gates={{t="dot",id=155625}},delegated=true},  -- moonfire_cat
      {id=5221,gates={},delegated=true},  -- shred
      {id=285381,gates={{t="dot",id=285381}},delegated=true},  -- primal_wrath
      {id=8936,gates={{t="buff",id=16974}},delegated=true},  -- regrowth
    },
  },
  ["DRUID_3"] = {
    st = {
      {id=1822,gates={{t="buff",id=5215}}},  -- rake
      {id=6807,gates={{t="buff",id=441583}}},  -- maul
      {id=155835,gates={{t="cd"}}},  -- bristling_fur
      {id=22812,gates={{t="buff",id=270100}}},  -- barkskin
      {id=204066,gates={}},  -- lunar_beam
      {id=391528,gates={},delegated=true},  -- convoke_the_spirits
      {id=400254,gates={},delegated=true},  -- raze
      {id=192081,gates={{t="buff",id=192081,neg=true},{t="cd"}},delegated=true},  -- ironfur
      {id=22568,gates={},delegated=true},  -- ferocious_bite
      {id=1079,gates={},delegated=true},  -- rip
      {id=33917,gates={{t="buff",id=210706}},delegated=true},  -- mangle
      {id=5221,gates={{t="cd"},{t="buff",id=768,neg=true},{t="dot",id=1822}},delegated=true},  -- shred
      {id=8921,gates={{t="buff",id=203964},{t="buff",id=270100}}},  -- moonfire
      {id=78674,gates={},delegated=true},  -- starsurge
    },
  },
  ["DRUID_4"] = {
    st = {
      {id=1261867,gates={{t="buff",id=5215,neg=true},{t="buff",id=58984,neg=true}}},  -- heart_of_the_wild
      {id=1822,gates={},delegated=true},  -- rake
      {id=391528,gates={},delegated=true},  -- convoke_the_spirits
      {id=1079,gates={{t="dot",id=1079}}},  -- rip
      {id=93402,gates={{t="dot",id=93402}}},  -- sunfire
      {id=8921,gates={{t="dot",id=8921}}},  -- moonfire
      {id=194153,gates={},delegated=true},  -- starfire
      {id=78674,gates={},delegated=true},  -- starsurge
      {id=22568,gates={}},  -- ferocious_bite
      {id=5221,gates={},delegated=true},  -- shred
      {id=5176,gates={}},  -- wrath
    },
  },
  ["EVOKER_1"] = {
    st = {
      {id=351338,gates={},delegated=true},  -- quell
      {id=357210,gates={}},  -- deep_breath
      {id=375087,gates={{t="execute"}},delegated=true},  -- dragonrage
      {id=359073,gates={{t="buff",id=375087},{t="cd"}},delegated=true},  -- eternity_surge
      {id=361469,gates={{t="cd"},{t="buff",id=375087}},delegated=true},  -- living_flame
      {id=358267,gates={{t="buff",id=358267,neg=true}},delegated=true},  -- hover
      {id=370553,gates={{t="buff",id=375087},{t="cd"}}},  -- tip_the_scales
      {id=357208,gates={},delegated=true},  -- fire_breath
      {id=362969,gates={{t="buff",id=375087}},delegated=true},  -- azure_strike
      {id=368847,gates={},delegated=true},  -- firestorm
      {id=356995,gates={},delegated=true},  -- disintegrate
      {id=357211,gates={},delegated=true},  -- pyre
      {id=365261,gates={}},  -- emerald_blossom
      {id=360995,gates={}},  -- verdant_embrace
    },
    aoe = {
      {id=351338,gates={},delegated=true},  -- quell
      {id=358267,gates={{t="buff",id=358267,neg=true}},delegated=true},  -- hover
      {id=368847,gates={},delegated=true},  -- firestorm
      {id=357210,gates={{t="cd"}},delegated=true},  -- deep_breath
      {id=370553,gates={{t="cd"}},delegated=true},  -- tip_the_scales
      {id=357208,gates={{t="execute"}},delegated=true},  -- fire_breath
      {id=375087,gates={},delegated=true},  -- dragonrage
      {id=359073,gates={},delegated=true},  -- eternity_surge
      {id=357211,gates={},delegated=true},  -- pyre
      {id=356995,gates={},delegated=true},  -- disintegrate
      {id=361469,gates={{t="buff",id=369939}},delegated=true},  -- living_flame
      {id=362969,gates={}},  -- azure_strike
      {id=365261,gates={}},  -- emerald_blossom
      {id=360995,gates={}},  -- verdant_embrace
    },
  },
  ["EVOKER_3"] = {
    st = {
      {id=358267,gates={},delegated=true},  -- hover
      {id=409311,gates={},delegated=true},  -- prescience
      {id=395152,gates={},delegated=true},  -- ebon_might
      {id=362969,gates={{t="cd"}},delegated=true},  -- azure_strike
      {id=395160,gates={},delegated=true},  -- eruption
      {id=361469,gates={},delegated=true},  -- living_flame
      {id=390386,gates={},delegated=true},  -- fury_of_the_aspects
      {id=370553,gates={},delegated=true},  -- tip_the_scales
      {id=357208,gates={},delegated=true},  -- fire_breath
      {id=357210,gates={}},  -- deep_breath
      {id=403631,gates={{t="execute"}},delegated=true},  -- breath_of_eons
      {id=396286,gates={},delegated=true},  -- upheaval
      {id=404977,gates={},delegated=true},  -- time_skip
      {id=365261,gates={{t="buff",id=369297}},delegated=true},  -- emerald_blossom
      {id=360827,gates={},delegated=true},  -- blistering_scales
    },
  },
  ["HUNTER_1"] = {
    st = {
      {id=53351,gates={}},  -- kill_shot
      {id=19574,gates={},delegated=true},  -- bestial_wrath
      {id=1272099,gates={}},  -- bloodshed
      {id=34026,gates={},delegated=true},  -- kill_command
      {id=217200,gates={{t="dot",id=217200}},delegated=true},  -- barbed_shot
      {id=193455,gates={{t="buff",id=466990,neg=true}}},  -- cobra_shot
    },
    aoe = {
      {id=53351,gates={}},  -- kill_shot
      {id=19574,gates={},delegated=true},  -- bestial_wrath
      {id=217200,gates={{t="dot",id=217200}},delegated=true},  -- barbed_shot
      {id=1272099,gates={}},  -- bloodshed
      {id=212431,gates={}},  -- explosive_shot
      {id=34026,gates={},delegated=true},  -- kill_command
      {id=193455,gates={{t="buff",id=466990,neg=true}},delegated=true},  -- cobra_shot
    },
  },
  ["HUNTER_2"] = {
    st = {
      {id=260243,gates={},delegated=true},  -- volley
      {id=212431,gates={{t="buff",id=194595,neg=true},{t="buff",id=288613,neg=true}},delegated=true},  -- explosive_shot
      {id=56641,gates={{t="buff",id=288613,neg=true},{t="cd"}},delegated=true},  -- steady_shot
      {id=288613,gates={},delegated=true},  -- trueshot
      {id=466930,gates={{t="buff",id=260240}},delegated=true},  -- black_arrow
      {id=19434,gates={},delegated=true},  -- aimed_shot
      {id=257044,gates={},delegated=true},  -- rapid_fire
      {id=185358,gates={{t="buff",id=260240}},delegated=true},  -- arcane_shot
      {id=53351,gates={{t="buff",id=260240}},delegated=true},  -- kill_shot
    },
    cleave = {
      {id=212431,gates={{t="buff",id=288613,neg=true}},delegated=true},  -- explosive_shot
      {id=466930,gates={},delegated=true},  -- black_arrow
      {id=257044,gates={{t="buff",id=389019,neg=true}},delegated=true},  -- rapid_fire
      {id=260243,gates={},delegated=true},  -- volley
      {id=288613,gates={},delegated=true},  -- trueshot
      {id=56641,gates={{t="buff",id=288613,neg=true}},delegated=true},  -- steady_shot
      {id=19434,gates={{t="buff",id=288613}},delegated=true},  -- aimed_shot
      {id=185358,gates={{t="buff",id=260240}},delegated=true},  -- arcane_shot
      {id=53351,gates={{t="buff",id=260240}},delegated=true},  -- kill_shot
      {id=257620,gates={{t="buff",id=260240}},delegated=true},  -- multishot
    },
    aoe = {
      {id=260243,gates={},delegated=true},  -- volley
      {id=212431,gates={{t="buff",id=288613,neg=true}},delegated=true},  -- explosive_shot
      {id=466930,gates={},delegated=true},  -- black_arrow
      {id=257044,gates={{t="buff",id=389019,neg=true}},delegated=true},  -- rapid_fire
      {id=288613,gates={},delegated=true},  -- trueshot
      {id=56641,gates={{t="buff",id=288613,neg=true}},delegated=true},  -- steady_shot
      {id=257620,gates={},delegated=true},  -- multishot
      {id=19434,gates={},delegated=true},  -- aimed_shot
      {id=53351,gates={{t="buff",id=257621},{t="buff",id=260240}},delegated=true},  -- kill_shot
      {id=185358,gates={{t="buff",id=260240}},delegated=true},  -- arcane_shot
    },
  },
  ["HUNTER_3"] = {
    st = {
      {id=190925,gates={},delegated=true},  -- harpoon
      {id=187707,gates={}},  -- muzzle
      {id=186289,gates={},delegated=true},  -- aspect_of_the_eagle
      {id=34026,gates={},delegated=true},  -- kill_command
      {id=203413,gates={},delegated=true},  -- fury_of_the_eagle
      {id=259495,gates={},delegated=true},  -- wildfire_bomb
      {id=212431,gates={}},  -- explosive_shot
      {id=53351,gates={}},  -- kill_shot
    },
    aoe = {
      {id=190925,gates={},delegated=true},  -- harpoon
      {id=187707,gates={}},  -- muzzle
      {id=186289,gates={},delegated=true},  -- aspect_of_the_eagle
      {id=34026,gates={},delegated=true},  -- kill_command
      {id=203413,gates={},delegated=true},  -- fury_of_the_eagle
      {id=259495,gates={},delegated=true},  -- wildfire_bomb
      {id=212431,gates={},delegated=true},  -- explosive_shot
      {id=53351,gates={},delegated=true},  -- kill_shot
    },
  },
  ["MAGE_1"] = {
    st = {
      {id=2139,gates={}},  -- counterspell
      {id=44425,gates={},delegated=true},  -- arcane_barrage
      {id=321507,gates={},delegated=true},  -- touch_of_the_magi
      {id=30451,gates={{t="buff",id=205025}}},  -- arcane_blast
      {id=153626,gates={},delegated=true},  -- arcane_orb
      {id=12051,gates={},delegated=true},  -- evocation
      {id=5143,gates={},delegated=true},  -- arcane_missiles
      {id=365350,gates={},delegated=true},  -- arcane_surge
      {id=314791,gates={},delegated=true},  -- shifting_power
      {id=205025,gates={},delegated=true},  -- presence_of_mind
      {id=1449,gates={},delegated=true},  -- arcane_explosion
      {id=157980,gates={},delegated=true},  -- supernova
    },
  },
  ["MAGE_2"] = {
    st = {
      {id=190319,gates={{t="buff",id=190319,neg=true}},delegated=true},  -- combustion
      {id=108853,gates={{t="buff",id=190319},{t="buff",id=195283,neg=true}},delegated=true},  -- fire_blast
      {id=2120,gates={},delegated=true},  -- flamestrike
      {id=11366,gates={},delegated=true},  -- pyroblast
      {id=153561,gates={},delegated=true},  -- meteor
      {id=2948,gates={{t="buff",id=190319,neg=true}},delegated=true},  -- scorch
      {id=133,gates={{t="buff",id=190319,neg=true}}},  -- fireball
      {id=314791,gates={{t="cd"}}},  -- shifting_power
    },
  },
  ["MAGE_3"] = {
    st = {
      {id=2139,gates={}},  -- counterspell
      {id=44614,gates={},delegated=true},  -- flurry
      {id=84714,gates={},delegated=true},  -- frozen_orb
      {id=1247777,gates={},delegated=true},  -- comet_storm
      {id=314791,gates={{t="cd"}},delegated=true},  -- shifting_power
      {id=30455,gates={},delegated=true},  -- ice_lance
      {id=431044,gates={}},  -- frostfire_bolt
      {id=157997,gates={}},  -- ice_nova
      {id=205021,gates={},delegated=true},  -- ray_of_frost
      {id=190356,gates={{t="buff",id=270233}},delegated=true},  -- blizzard
      {id=116,gates={}},  -- frostbolt
    },
    cleave = {
      {id=2139,gates={}},  -- counterspell
      {id=44614,gates={},delegated=true},  -- flurry
      {id=84714,gates={},delegated=true},  -- frozen_orb
      {id=1247777,gates={}},  -- comet_storm
      {id=190356,gates={{t="buff",id=270233}},delegated=true},  -- blizzard
      {id=314791,gates={{t="cd"}},delegated=true},  -- shifting_power
      {id=30455,gates={{t="buff",id=112965}}},  -- ice_lance
      {id=431044,gates={}},  -- frostfire_bolt
      {id=157997,gates={}},  -- ice_nova
      {id=116,gates={},delegated=true},  -- frostbolt
      {id=205021,gates={},delegated=true},  -- ray_of_frost
    },
    aoe = {
      {id=2139,gates={}},  -- counterspell
      {id=44614,gates={},delegated=true},  -- flurry
      {id=84714,gates={},delegated=true},  -- frozen_orb
      {id=120,gates={},delegated=true},  -- cone_of_cold
      {id=157997,gates={},delegated=true},  -- ice_nova
      {id=190356,gates={},delegated=true},  -- blizzard
      {id=431044,gates={},delegated=true},  -- frostfire_bolt
      {id=30455,gates={{t="cd"}},delegated=true},  -- ice_lance
      {id=1247777,gates={},delegated=true},  -- comet_storm
      {id=205021,gates={},delegated=true},  -- ray_of_frost
      {id=314791,gates={{t="cd"}},delegated=true},  -- shifting_power
      {id=116,gates={},delegated=true},  -- frostbolt
    },
  },
  ["MONK_1"] = {
    st = {
      {id=115399,gates={},delegated=true},  -- black_ox_brew
      {id=322507,gates={},delegated=true},  -- celestial_brew
      {id=100784,gates={}},  -- blackout_kick
      {id=123986,gates={},delegated=true},  -- chi_burst
      {id=387184,gates={}},  -- weapons_of_order
      {id=132578,gates={}},  -- invoke_niuzao
      {id=107428,gates={}},  -- rising_sun_kick
      {id=121253,gates={{t="buff",id=387184}},delegated=true},  -- keg_smash
      {id=100780,gates={{t="buff",id=196736}}},  -- tiger_palm
      {id=322729,gates={{t="buff",id=386965},{t="dot",id=115181}},delegated=true},  -- spinning_crane_kick
      {id=119582,gates={{t="buff",id=196736,neg=true}},delegated=true},  -- purifying_brew
      {id=115181,gates={},delegated=true},  -- breath_of_fire
      {id=325153,gates={},delegated=true},  -- exploding_keg
      {id=116847,gates={},delegated=true},  -- rushing_jade_wind
    },
  },
  ["MONK_2"] = {
    st = {
      {id=322109,gates={}},  -- touch_of_death
      {id=116680,gates={}},  -- thunder_focus_tea
      {id=322118,gates={}},  -- invoke_yulon
      {id=399491,gates={},delegated=true},  -- sheiluns_gift
      {id=443028,gates={}},  -- celestial_conduit
      {id=107428,gates={{t="buff",id=116680}}},  -- rising_sun_kick
      {id=101546,gates={},delegated=true},  -- spinning_crane_kick
      {id=123986,gates={}},  -- chi_burst
      {id=117952,gates={{t="buff",id=467316}}},  -- crackling_jade_lightning
      {id=388193,gates={}},  -- jadefire_stomp
      {id=100784,gates={},delegated=true},  -- blackout_kick
      {id=100780,gates={}},  -- tiger_palm
    },
  },
  ["MONK_3"] = {
    st = {
      {id=109132,gates={},delegated=true},  -- roll
      {id=115008,gates={},delegated=true},  -- chi_torpedo
      {id=101545,gates={},delegated=true},  -- flying_serpent_kick
      {id=116705,gates={},delegated=true},  -- spear_hand_strike
      {id=100780,gates={},delegated=true},  -- tiger_palm
      {id=107428,gates={}},  -- rising_sun_kick
      {id=137639,gates={},delegated=true},  -- storm_earth_and_fire
      {id=123904,gates={{t="cd"}},delegated=true},  -- invoke_xuen_the_white_tiger
      {id=122470,gates={}},  -- touch_of_karma
      {id=1217413,gates={},delegated=true},  -- slicing_winds
      {id=113656,gates={},delegated=true},  -- fists_of_fury
      {id=152175,gates={{t="cd"}},delegated=true},  -- whirling_dragon_punch
      {id=443028,gates={{t="buff",id=137639},{t="cd"},{t="buff",id=388661}},delegated=true},  -- celestial_conduit
      {id=343730,gates={},delegated=true},  -- spinning_crane_kick
      {id=325215,gates={}},  -- touch_of_death
      {id=392983,gates={{t="buff",id=388661,neg=true},{t="cd"}},delegated=true},  -- strike_of_the_windlord
      {id=261916,gates={{t="cd"}},delegated=true},  -- blackout_kick
      {id=117952,gates={{t="cd"},{t="buff",id=137639}},delegated=true},  -- crackling_jade_lightning
      {id=388193,gates={},delegated=true},  -- jadefire_stomp
      {id=123986,gates={},delegated=true},  -- chi_burst
    },
    aoe = {
      {id=109132,gates={},delegated=true},  -- roll
      {id=115008,gates={},delegated=true},  -- chi_torpedo
      {id=101545,gates={},delegated=true},  -- flying_serpent_kick
      {id=116705,gates={},delegated=true},  -- spear_hand_strike
      {id=137639,gates={},delegated=true},  -- storm_earth_and_fire
      {id=100780,gates={{t="cd"}},delegated=true},  -- tiger_palm
      {id=123904,gates={{t="cd"}},delegated=true},  -- invoke_xuen_the_white_tiger
      {id=122470,gates={}},  -- touch_of_karma
      {id=107428,gates={},delegated=true},  -- rising_sun_kick
      {id=152175,gates={},delegated=true},  -- whirling_dragon_punch
      {id=392983,gates={{t="cd"}}},  -- strike_of_the_windlord
      {id=1217413,gates={},delegated=true},  -- slicing_winds
      {id=343730,gates={},delegated=true},  -- spinning_crane_kick
      {id=443028,gates={{t="buff",id=137639},{t="cd"},{t="buff",id=388661}},delegated=true},  -- celestial_conduit
      {id=325215,gates={},delegated=true},  -- touch_of_death
      {id=261916,gates={{t="cd"}},delegated=true},  -- blackout_kick
      {id=113656,gates={},delegated=true},  -- fists_of_fury
      {id=117952,gates={{t="cd"}},delegated=true},  -- crackling_jade_lightning
      {id=388193,gates={},delegated=true},  -- jadefire_stomp
      {id=123986,gates={},delegated=true},  -- chi_burst
    },
  },
  ["PALADIN_2"] = {
    st = {
      {id=384376,gates={}},  -- avenging_wrath
      {id=375576,gates={}},  -- divine_toll
      {id=31850,gates={}},  -- ardent_defender
      {id=275779,gates={},delegated=true},  -- judgment
      {id=209202,gates={}},  -- eye_of_tyr
      {id=53600,gates={},delegated=true},  -- shield_of_the_righteous
      {id=1289728,gates={},delegated=true},  -- holy_armaments
      {id=204019,gates={}},  -- blessed_hammer
      {id=31935,gates={{t="buff",id=386653,neg=true}}},  -- avengers_shield
      {id=53595,gates={{t="buff",id=433015},{t="buff",id=384376,neg=true}}},  -- hammer_of_the_righteous
      {id=342348,gates={{t="buff",id=433015},{t="buff",id=384376,neg=true}}},  -- crusader_strike
      {id=327980,gates={},delegated=true},  -- consecration
      {id=1241288,gates={}},  -- hammer_of_wrath
      {id=315921,gates={},delegated=true},  -- word_of_glory
    },
  },
  ["PALADIN_3"] = {
    st = {
      {id=96231,gates={}},  -- rebuke
      {id=1261562,gates={{t="buff",id=432929,neg=true}},delegated=true},  -- shield_of_vengeance
      {id=343527,gates={{t="cd"}},delegated=true},  -- execution_sentence
      {id=384376,gates={},delegated=true},  -- avenging_wrath
      {id=1253598,gates={},delegated=true},  -- crusade
      {id=432929,gates={{t="buff",id=432929,neg=true}}},  -- divine_hammer
      {id=53385,gates={},delegated=true},  -- divine_storm
      {id=85256,gates={},delegated=true},  -- templars_verdict
      {id=184575,gates={{t="dot",id=383344},{t="cd"}}},  -- blade_of_justice
      {id=255937,gates={},delegated=true},  -- wake_of_ashes
      {id=375576,gates={},delegated=true},  -- divine_toll
      {id=1241288,gates={{t="buff",id=445200}},delegated=true},  -- hammer_of_wrath
      {id=315867,gates={}},  -- judgment
      {id=342348,gates={}},  -- crusader_strike
    },
  },
  ["PRIEST_3"] = {
    st = {
      {id=1230339,gates={},delegated=true},  -- mindbender
      {id=32379,gates={},delegated=true},  -- shadow_word_death
      {id=450405,gates={},delegated=true},  -- void_blast
      {id=228266,gates={{t="cd"}},delegated=true},  -- void_bolt
      {id=263165,gates={},delegated=true},  -- void_torrent
      {id=34914,gates={{t="dot",id=34914},{t="execute"}},delegated=true},  -- vampiric_touch
      {id=8092,gates={},delegated=true},  -- mind_blast
      {id=120517,gates={}},  -- halo
      {id=132157,gates={},delegated=true},  -- holy_nova
      {id=15407,gates={}},  -- mind_flay
      {id=589,gates={}},  -- shadow_word_pain
    },
    aoe = {
      {id=34914,gates={{t="buff",id=447444,neg=true},{t="dot",id=34914}},delegated=true},  -- vampiric_touch
      {id=2061,gates={},delegated=true},  -- flash_heal
      {id=10060,gates={},delegated=true},  -- power_infusion
      {id=120517,gates={},delegated=true},  -- halo
      {id=19236,gates={},delegated=true},  -- desperate_prayer
      {id=1230339,gates={},delegated=true},  -- mindbender
      {id=32379,gates={},delegated=true},  -- shadow_word_death
      {id=450405,gates={},delegated=true},  -- void_blast
      {id=228266,gates={{t="cd"}},delegated=true},  -- void_bolt
      {id=263165,gates={},delegated=true},  -- void_torrent
      {id=8092,gates={},delegated=true},  -- mind_blast
      {id=132157,gates={},delegated=true},  -- holy_nova
      {id=15407,gates={}},  -- mind_flay
      {id=589,gates={}},  -- shadow_word_pain
    },
  },
  ["ROGUE_1"] = {
    st = {
      {id=1784,gates={}},  -- stealth
      {id=1766,gates={}},  -- kick
      {id=8676,gates={},delegated=true},  -- ambush
      {id=5938,gates={{t="dot",id=385627},{t="buff",id=32645}},delegated=true},  -- shiv
      {id=32645,gates={{t="dot",id=385627}},delegated=true},  -- envenom
      {id=1943,gates={{t="dot",id=1943}}},  -- rupture
      {id=703,gates={{t="execute"}},delegated=true},  -- garrote
      {id=360194,gates={},delegated=true},  -- deathmark
      {id=385627,gates={},delegated=true},  -- kingsbane
      {id=469779,gates={},delegated=true},  -- thistle_tea
      {id=1247227,gates={{t="dot",id=1247227},{t="buff",id=457058,neg=true}},delegated=true},  -- crimson_tempest
      {id=1329,gates={},delegated=true},  -- mutilate
      {id=51723,gates={{t="buff",id=1248793}},delegated=true},  -- fan_of_knives
    },
    aoe = {
      {id=1784,gates={}},  -- stealth
      {id=1766,gates={}},  -- kick
      {id=8676,gates={},delegated=true},  -- ambush
      {id=5938,gates={{t="dot",id=385627},{t="buff",id=32645}},delegated=true},  -- shiv
      {id=32645,gates={{t="dot",id=385627}},delegated=true},  -- envenom
      {id=1943,gates={{t="dot",id=1943}}},  -- rupture
      {id=703,gates={{t="execute"}},delegated=true},  -- garrote
      {id=360194,gates={},delegated=true},  -- deathmark
      {id=385627,gates={},delegated=true},  -- kingsbane
      {id=469779,gates={},delegated=true},  -- thistle_tea
      {id=1856,gates={{t="dot",id=360194}},delegated=true},  -- vanish
      {id=1247227,gates={{t="dot",id=1247227},{t="buff",id=457058,neg=true}},delegated=true},  -- crimson_tempest
      {id=1329,gates={},delegated=true},  -- mutilate
      {id=51723,gates={{t="buff",id=1248793}},delegated=true},  -- fan_of_knives
    },
  },
  ["ROGUE_2"] = {
    st = {
      {id=1784,gates={}},  -- stealth
      {id=1766,gates={}},  -- kick
      {id=13750,gates={{t="buff",id=13750,neg=true}},delegated=true},  -- adrenaline_rush
      {id=2983,gates={},delegated=true},  -- sprint
      {id=13877,gates={},delegated=true},  -- blade_flurry
      {id=381989,gates={},delegated=true},  -- keep_it_rolling
      {id=1214909,gates={},delegated=true},  -- roll_the_bones
      {id=1856,gates={{t="buff",id=13750},{t="cd"}},delegated=true},  -- vanish
      {id=51690,gates={}},  -- killing_spree
      {id=441423,gates={}},  -- coup_de_grace
      {id=315341,gates={},delegated=true},  -- between_the_eyes
      {id=2098,gates={}},  -- dispatch
      {id=271877,gates={},delegated=true},  -- blade_rush
      {id=185763,gates={},delegated=true},  -- pistol_shot
      {id=8676,gates={}},  -- ambush
      {id=193315,gates={{t="buff",id=441274}},delegated=true},  -- sinister_strike
    },
  },
  ["ROGUE_3"] = {
    st = {
      {id=1784,gates={}},  -- stealth
      {id=121471,gates={{t="buff",id=185313},{t="buff",id=343160,neg=true}},delegated=true},  -- shadow_blades
      {id=469779,gates={{t="buff",id=469779,neg=true}},delegated=true},  -- thistle_tea
      {id=323654,gates={},delegated=true},  -- flagellation
      {id=185313,gates={},delegated=true},  -- shadow_dance
      {id=1856,gates={{t="buff",id=108208,neg=true}},delegated=true},  -- vanish
      {id=280719,gates={},delegated=true},  -- secret_technique
      {id=441423,gates={},delegated=true},  -- coup_de_grace
      {id=319175,gates={},delegated=true},  -- black_powder
      {id=196819,gates={},delegated=true},  -- eviscerate
      {id=1264764,gates={},delegated=true},  -- shuriken_tornado
      {id=197835,gates={},delegated=true},  -- shuriken_storm
      {id=53,gates={},delegated=true},  -- backstab
      {id=200758,gates={},delegated=true},  -- gloomblade
      {id=185438,gates={},delegated=true},  -- shadowstrike
      {id=426591,gates={},delegated=true},  -- goremaws_bite
    },
  },
  ["SHAMAN_1"] = {
    st = {
      {id=79206,gates={},delegated=true},  -- spiritwalkers_grace
      {id=57994,gates={}},  -- wind_shear
      {id=192106,gates={{t="buff",id=192106,neg=true}}},  -- lightning_shield
      {id=378081,gates={}},  -- natures_swiftness
      {id=198067,gates={}},  -- fire_elemental
      {id=192249,gates={},delegated=true},  -- storm_elemental
      {id=191634,gates={},delegated=true},  -- stormkeeper
      {id=192222,gates={{t="buff",id=16166,neg=true}},delegated=true},  -- liquid_magma_totem
      {id=470411,gates={{t="buff",id=16166,neg=true}},delegated=true},  -- flame_shock
      {id=375982,gates={}},  -- primordial_wave
      {id=443454,gates={}},  -- ancestral_swiftness
      {id=114050,gates={},delegated=true},  -- ascendance
      {id=454009,gates={},delegated=true},  -- tempest
      {id=188196,gates={},delegated=true},  -- lightning_bolt
      {id=117014,gates={},delegated=true},  -- elemental_blast
      {id=8042,gates={},delegated=true},  -- earth_shock
      {id=210714,gates={},delegated=true},  -- icefury
      {id=51505,gates={{t="buff",id=16166,neg=true}},delegated=true},  -- lava_burst
      {id=61882,gates={},delegated=true},  -- earthquake
      {id=196840,gates={{t="buff",id=114050,neg=true},{t="buff",id=191634,neg=true}},delegated=true},  -- frost_shock
    },
    aoe = {
      {id=79206,gates={},delegated=true},  -- spiritwalkers_grace
      {id=57994,gates={}},  -- wind_shear
      {id=192106,gates={{t="buff",id=192106,neg=true}}},  -- lightning_shield
      {id=378081,gates={}},  -- natures_swiftness
      {id=198067,gates={}},  -- fire_elemental
      {id=192249,gates={},delegated=true},  -- storm_elemental
      {id=191634,gates={},delegated=true},  -- stormkeeper
      {id=192222,gates={},delegated=true},  -- liquid_magma_totem
      {id=470411,gates={{t="cd"}},delegated=true},  -- flame_shock
      {id=375982,gates={{t="cd"}},delegated=true},  -- primordial_wave
      {id=443454,gates={}},  -- ancestral_swiftness
      {id=114050,gates={},delegated=true},  -- ascendance
      {id=454009,gates={},delegated=true},  -- tempest
      {id=188196,gates={{t="buff",id=191634}},delegated=true},  -- lightning_bolt
      {id=188443,gates={},delegated=true},  -- chain_lightning
      {id=51505,gates={{t="buff",id=77756},{t="buff",id=16166,neg=true}},delegated=true},  -- lava_burst
      {id=61882,gates={},delegated=true},  -- earthquake
      {id=117014,gates={},delegated=true},  -- elemental_blast
      {id=8042,gates={},delegated=true},  -- earth_shock
      {id=210714,gates={},delegated=true},  -- icefury
      {id=196840,gates={{t="buff",id=114050,neg=true},{t="buff",id=191634,neg=true}},delegated=true},  -- frost_shock
    },
  },
  ["SHAMAN_2"] = {
    st = {
      {id=2825,gates={}},  -- bloodlust
      {id=470411,gates={{t="dot",id=470411}}},  -- flame_shock
      {id=470057,gates={{t="buff",id=114050,neg=true}},delegated=true},  -- voltaic_blaze
      {id=375982,gates={{t="dot",id=470411}},delegated=true},  -- primordial_wave
      {id=51533,gates={},delegated=true},  -- feral_spirit
      {id=384352,gates={},delegated=true},  -- doom_winds
      {id=114050,gates={},delegated=true},  -- ascendance
      {id=1218047,gates={},delegated=true},  -- primordial_storm
      {id=115356,gates={}},  -- windstrike
      {id=117014,gates={},delegated=true},  -- elemental_blast
      {id=454009,gates={},delegated=true},  -- tempest
      {id=188196,gates={},delegated=true},  -- lightning_bolt
      {id=342240,gates={}},  -- ice_strike
      {id=17364,gates={}},  -- stormstrike
      {id=187874,gates={}},  -- crash_lightning
      {id=60103,gates={}},  -- lava_lash
      {id=196840,gates={{t="buff",id=454009},{t="buff",id=342240}},delegated=true},  -- frost_shock
      {id=378081,gates={{t="buff",id=454009}},delegated=true},  -- natures_swiftness
      {id=197214,gates={}},  -- sundering
      {id=333974,gates={},delegated=true},  -- fire_nova
      {id=198103,gates={}},  -- earth_elemental
      {id=455630,gates={},delegated=true},  -- surging_totem
      {id=108285,gates={}},  -- totemic_recall
      {id=51505,gates={},delegated=true},  -- lava_burst
    },
    aoe = {
      {id=2825,gates={}},  -- bloodlust
      {id=51533,gates={},delegated=true},  -- feral_spirit
      {id=470411,gates={{t="dot",id=470411}}},  -- flame_shock
      {id=187874,gates={},delegated=true},  -- crash_lightning
      {id=470057,gates={},delegated=true},  -- voltaic_blaze
      {id=60103,gates={{t="dot",id=470411}},delegated=true},  -- lava_lash
      {id=375982,gates={{t="dot",id=470411}},delegated=true},  -- primordial_wave
      {id=384352,gates={},delegated=true},  -- doom_winds
      {id=114050,gates={},delegated=true},  -- ascendance
      {id=1218047,gates={},delegated=true},  -- primordial_storm
      {id=454009,gates={{t="buff",id=114050,neg=true}},delegated=true},  -- tempest
      {id=115356,gates={},delegated=true},  -- windstrike
      {id=188443,gates={{t="buff",id=384352}},delegated=true},  -- chain_lightning
      {id=17364,gates={},delegated=true},  -- stormstrike
      {id=333974,gates={},delegated=true},  -- fire_nova
      {id=197214,gates={{t="buff",id=384352}}},  -- sundering
      {id=342240,gates={{t="buff",id=342240,neg=true}}},  -- ice_strike
      {id=196840,gates={{t="buff",id=334195}}},  -- frost_shock
      {id=455630,gates={},delegated=true},  -- surging_totem
      {id=108285,gates={}},  -- totemic_recall
      {id=117014,gates={{t="cd"}},delegated=true},  -- elemental_blast
      {id=188196,gates={{t="buff",id=375982}},delegated=true},  -- lightning_bolt
      {id=51505,gates={},delegated=true},  -- lava_burst
    },
  },
  ["WARLOCK_1"] = {
    st = {
      {id=388667,gates={},delegated=true},  -- drain_soul
      {id=324536,gates={},delegated=true},  -- malefic_rapture
      {id=980,gates={},delegated=true},  -- agony
      {id=48181,gates={{t="buff",id=108558}},delegated=true},  -- haunt
      {id=1259790,gates={},delegated=true},  -- unstable_affliction
      {id=445465,gates={},delegated=true},  -- wither
      {id=172,gates={},delegated=true},  -- corruption
      {id=686,gates={{t="buff",id=108558},{t="buff",id=387075},{t="cd"}},delegated=true},  -- shadow_bolt
      {id=278350,gates={{t="dot",id=980},{t="dot",id=1259790}},delegated=true},  -- vile_taint
      {id=205179,gates={{t="dot",id=980},{t="dot",id=1259790}},delegated=true},  -- phantom_singularity
      {id=386997,gates={},delegated=true},  -- soul_rot
      {id=205180,gates={},delegated=true},  -- summon_darkglare
      {id=430014,gates={},delegated=true},  -- malevolence
    },
    cleave = {
      {id=388667,gates={},delegated=true},  -- drain_soul
      {id=324536,gates={},delegated=true},  -- malefic_rapture
      {id=980,gates={},delegated=true},  -- agony
      {id=445465,gates={},delegated=true},  -- wither
      {id=172,gates={},delegated=true},  -- corruption
      {id=48181,gates={{t="buff",id=108558}},delegated=true},  -- haunt
      {id=1259790,gates={},delegated=true},  -- unstable_affliction
      {id=686,gates={},delegated=true},  -- shadow_bolt
      {id=278350,gates={},delegated=true},  -- vile_taint
      {id=205179,gates={},delegated=true},  -- phantom_singularity
      {id=386997,gates={},delegated=true},  -- soul_rot
      {id=205180,gates={},delegated=true},  -- summon_darkglare
      {id=430014,gates={},delegated=true},  -- malevolence
    },
    aoe = {
      {id=388667,gates={},delegated=true},  -- drain_soul
      {id=324536,gates={},delegated=true},  -- malefic_rapture
      {id=48181,gates={},delegated=true},  -- haunt
      {id=980,gates={{t="dot",id=980},{t="cd"}}},  -- agony
      {id=278350,gates={},delegated=true},  -- vile_taint
      {id=1259790,gates={},delegated=true},  -- unstable_affliction
      {id=205179,gates={{t="dot",id=980}},delegated=true},  -- phantom_singularity
      {id=386997,gates={{t="dot",id=980}},delegated=true},  -- soul_rot
      {id=27243,gates={},delegated=true},  -- seed_of_corruption
      {id=205180,gates={{t="cd"}},delegated=true},  -- summon_darkglare
      {id=430014,gates={},delegated=true},  -- malevolence
      {id=445465,gates={{t="dot",id=445465}},delegated=true},  -- wither
      {id=172,gates={{t="dot",id=172}},delegated=true},  -- corruption
      {id=686,gates={},delegated=true},  -- shadow_bolt
    },
  },
  ["WARLOCK_2"] = {
    st = {
      {id=1250273,gates={{t="cd"}},delegated=true},  -- hand_of_guldan
      {id=265187,gates={},delegated=true},  -- summon_demonic_tyrant
      {id=111898,gates={{t="cd"}}},  -- grimoire_felguard
      {id=264119,gates={{t="cd"}},delegated=true},  -- summon_vilefiend
      {id=104316,gates={},delegated=true},  -- call_dreadstalkers
      {id=264178,gates={},delegated=true},  -- demonbolt
      {id=267171,gates={},delegated=true},  -- demonic_strength
      {id=267211,gates={}},  -- bilescourge_bombers
      {id=196277,gates={},delegated=true},  -- implosion
      {id=428522,gates={}},  -- ruination
      {id=264130,gates={},delegated=true},  -- power_siphon
      {id=686,gates={}},  -- shadow_bolt
    },
  },
  ["WARLOCK_3"] = {
    st = {
      {id=430014,gates={{t="cd"}}},  -- malevolence
      {id=1122,gates={},delegated=true},  -- summon_infernal
      {id=116858,gates={},delegated=true},  -- chaos_bolt
      {id=6353,gates={{t="buff",id=387176}},delegated=true},  -- soul_fire
      {id=445465,gates={{t="execute"}},delegated=true},  -- wither
      {id=17962,gates={},delegated=true},  -- conflagrate
      {id=17877,gates={},delegated=true},  -- shadowburn
      {id=428522,gates={}},  -- ruination
      {id=152108,gates={},delegated=true},  -- cataclysm
      {id=196447,gates={},delegated=true},  -- channel_demonfire
      {id=348,gates={{t="execute"}},delegated=true},  -- immolate
      {id=387976,gates={}},  -- dimensional_rift
      {id=29722,gates={}},  -- incinerate
    },
    cleave = {
      {id=17962,gates={{t="buff",id=196406,neg=true}},delegated=true},  -- conflagrate
      {id=6353,gates={},delegated=true},  -- soul_fire
      {id=152108,gates={},delegated=true},  -- cataclysm
      {id=348,gates={{t="dot",id=348}},delegated=true},  -- immolate
      {id=445465,gates={{t="dot",id=445465}},delegated=true},  -- wither
      {id=17877,gates={},delegated=true},  -- shadowburn
      {id=116858,gates={},delegated=true},  -- chaos_bolt
      {id=5740,gates={}},  -- rain_of_fire
      {id=196447,gates={},delegated=true},  -- channel_demonfire
      {id=387976,gates={},delegated=true},  -- dimensional_rift
      {id=29722,gates={},delegated=true},  -- incinerate
      {id=430014,gates={},delegated=true},  -- malevolence
      {id=80240,gates={{t="execute"}},delegated=true},  -- havoc
      {id=428522,gates={},delegated=true},  -- ruination
      {id=1122,gates={}},  -- summon_infernal
    },
    aoe = {
      {id=430014,gates={{t="cd"}},delegated=true},  -- malevolence
      {id=116858,gates={},delegated=true},  -- chaos_bolt
      {id=17962,gates={{t="buff",id=196406,neg=true}},delegated=true},  -- conflagrate
      {id=6353,gates={},delegated=true},  -- soul_fire
      {id=152108,gates={},delegated=true},  -- cataclysm
      {id=348,gates={{t="dot",id=348}},delegated=true},  -- immolate
      {id=445465,gates={{t="dot",id=445465}},delegated=true},  -- wither
      {id=17877,gates={},delegated=true},  -- shadowburn
      {id=5740,gates={}},  -- rain_of_fire
      {id=196447,gates={},delegated=true},  -- channel_demonfire
      {id=387976,gates={},delegated=true},  -- dimensional_rift
      {id=29722,gates={},delegated=true},  -- incinerate
      {id=428522,gates={}},  -- ruination
      {id=80240,gates={{t="execute"}},delegated=true},  -- havoc
      {id=1122,gates={},delegated=true},  -- summon_infernal
    },
  },
  ["WARRIOR_1"] = {
    st = {
      {id=100,gates={},delegated=true},  -- charge
      {id=6552,gates={},delegated=true},  -- pummel
      {id=260708,gates={}},  -- sweeping_strikes
      {id=772,gates={{t="dot",id=772}}},  -- rend
      {id=384318,gates={}},  -- thunderous_roar
      {id=376079,gates={}},  -- champions_spear
      {id=228920,gates={{t="cd"}},delegated=true},  -- ravager
      {id=107574,gates={}},  -- avatar
      {id=167105,gates={}},  -- colossus_smash
      {id=262161,gates={{t="cd"}}},  -- warbreaker
      {id=163201,gates={},delegated=true},  -- execute
      {id=260643,gates={}},  -- skullsplitter
      {id=436358,gates={},delegated=true},  -- demolish
      {id=12294,gates={},delegated=true},  -- mortal_strike
      {id=7384,gates={},delegated=true},  -- overpower
      {id=227847,gates={}},  -- bladestorm
      {id=384110,gates={}},  -- wrecking_throw
      {id=1464,gates={}},  -- slam
      {id=107570,gates={{t="buff",id=227847}}},  -- storm_bolt
    },
    cleave = {
      {id=100,gates={},delegated=true},  -- charge
      {id=6552,gates={},delegated=true},  -- pummel
      {id=260708,gates={}},  -- sweeping_strikes
      {id=772,gates={{t="dot",id=772}}},  -- rend
      {id=384318,gates={}},  -- thunderous_roar
      {id=376079,gates={}},  -- champions_spear
      {id=228920,gates={{t="cd"}},delegated=true},  -- ravager
      {id=107574,gates={}},  -- avatar
      {id=167105,gates={}},  -- colossus_smash
      {id=262161,gates={{t="cd"}}},  -- warbreaker
      {id=163201,gates={},delegated=true},  -- execute
      {id=260643,gates={}},  -- skullsplitter
      {id=436358,gates={},delegated=true},  -- demolish
      {id=12294,gates={},delegated=true},  -- mortal_strike
      {id=7384,gates={},delegated=true},  -- overpower
      {id=227847,gates={}},  -- bladestorm
      {id=384110,gates={}},  -- wrecking_throw
      {id=6343,gates={{t="dot",id=772},{t="buff",id=260708,neg=true}}},  -- thunder_clap
      {id=1680,gates={}},  -- whirlwind
      {id=845,gates={}},  -- cleave
      {id=1464,gates={}},  -- slam
      {id=107570,gates={{t="buff",id=227847}}},  -- storm_bolt
    },
    aoe = {
      {id=100,gates={},delegated=true},  -- charge
      {id=6552,gates={},delegated=true},  -- pummel
      {id=845,gates={{t="dot",id=1261060}}},  -- cleave
      {id=6343,gates={{t="dot",id=772}}},  -- thunder_clap
      {id=384318,gates={}},  -- thunderous_roar
      {id=260708,gates={}},  -- sweeping_strikes
      {id=262161,gates={{t="cd"}}},  -- warbreaker
      {id=167105,gates={{t="cd"}}},  -- colossus_smash
      {id=376079,gates={}},  -- champions_spear
      {id=228920,gates={}},  -- ravager
      {id=107574,gates={}},  -- avatar
      {id=436358,gates={},delegated=true},  -- demolish
      {id=227847,gates={},delegated=true},  -- bladestorm
      {id=12294,gates={}},  -- mortal_strike
      {id=260643,gates={}},  -- skullsplitter
      {id=7384,gates={}},  -- overpower
      {id=163201,gates={}},  -- execute
      {id=384110,gates={}},  -- wrecking_throw
      {id=1680,gates={}},  -- whirlwind
      {id=772,gates={{t="dot",id=772}}},  -- rend
      {id=1464,gates={}},  -- slam
      {id=107570,gates={{t="buff",id=227847}}},  -- storm_bolt
    },
  },
  ["WARRIOR_2"] = {
    st = {
      {id=100,gates={},delegated=true},  -- charge
      {id=6544,gates={},delegated=true},  -- heroic_leap
      {id=6552,gates={},delegated=true},  -- pummel
      {id=1719,gates={}},  -- recklessness
      {id=107574,gates={}},  -- avatar
      {id=5308,gates={{t="buff",id=392536}},delegated=true},  -- execute
      {id=384318,gates={{t="buff",id=184361}}},  -- thunderous_roar
      {id=376079,gates={{t="cd"},{t="buff",id=184361}},delegated=true},  -- champions_spear
      {id=385059,gates={},delegated=true},  -- odyns_fury
      {id=227847,gates={{t="buff",id=184361}},delegated=true},  -- bladestorm
      {id=190411,gates={},delegated=true},  -- whirlwind
      {id=315720,gates={{t="buff",id=446085}}},  -- onslaught
      {id=184367,gates={},delegated=true},  -- rampage
      {id=113344,gates={},delegated=true},  -- bloodbath
      {id=85288,gates={{t="buff",id=446085}},delegated=true},  -- raging_blow
      {id=23881,gates={{t="execute"},{t="buff",id=446085},{t="buff",id=184361}},delegated=true},  -- bloodthirst
      {id=384110,gates={}},  -- wrecking_throw
      {id=107570,gates={{t="buff",id=227847}}},  -- storm_bolt
      {id=228920,gates={}},  -- ravager
      {id=6343,gates={},delegated=true},  -- thunder_clap
      {id=435607,gates={{t="buff",id=184361}}},  -- thunder_blast
    },
  },
  ["WARRIOR_3"] = {
    st = {
      {id=100,gates={},delegated=true},  -- charge
      {id=107574,gates={},delegated=true},  -- avatar
      {id=871,gates={{t="buff",id=107574,neg=true}}},  -- shield_wall
      {id=190456,gates={{t="execute"},{t="cd"}},delegated=true},  -- ignore_pain
      {id=12975,gates={},delegated=true},  -- last_stand
      {id=228920,gates={}},  -- ravager
      {id=1160,gates={}},  -- demoralizing_shout
      {id=376079,gates={}},  -- champions_spear
      {id=435607,gates={},delegated=true},  -- thunder_blast
      {id=436358,gates={},delegated=true},  -- demolish
      {id=384318,gates={}},  -- thunderous_roar
      {id=385952,gates={}},  -- shield_charge
      {id=231847,gates={},delegated=true},  -- shield_block
      {id=23922,gates={},delegated=true},  -- shield_slam
      {id=163201,gates={},delegated=true},  -- execute
      {id=6343,gates={{t="dot",id=772},{t="buff",id=386477,neg=true}}},  -- thunder_clap
      {id=6572,gates={},delegated=true},  -- revenge
      {id=20243,gates={}},  -- devastate
    },
    aoe = {
      {id=100,gates={},delegated=true},  -- charge
      {id=107574,gates={},delegated=true},  -- avatar
      {id=871,gates={{t="buff",id=107574,neg=true}}},  -- shield_wall
      {id=190456,gates={{t="execute"},{t="cd"}},delegated=true},  -- ignore_pain
      {id=12975,gates={},delegated=true},  -- last_stand
      {id=228920,gates={}},  -- ravager
      {id=1160,gates={}},  -- demoralizing_shout
      {id=376079,gates={}},  -- champions_spear
      {id=435607,gates={},delegated=true},  -- thunder_blast
      {id=436358,gates={},delegated=true},  -- demolish
      {id=384318,gates={}},  -- thunderous_roar
      {id=385952,gates={}},  -- shield_charge
      {id=231847,gates={},delegated=true},  -- shield_block
      {id=6343,gates={{t="dot",id=772}}},  -- thunder_clap
      {id=163201,gates={},delegated=true},  -- execute
      {id=6572,gates={},delegated=true},  -- revenge
      {id=23922,gates={},delegated=true},  -- shield_slam
      {id=20243,gates={}},  -- devastate
    },
  },
})
