# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/AuraRequirements.lua from client data CSV exports.
#
# Caster-aura requirements ([spellID] = required aura spellID): spells only
# castable while a specific aura is on the player. The queue sinks them while
# the aura is absent (aura presence is combat-safe via the instance-ID cache).
#
# Deliberately narrow: only CasterAuraSpell is emitted. CasterAuraState is an
# internal engine flag with no lookup API (Victory Rush-style states are covered
# by Blizzard's proc overlay); Target* columns are combat-secret territory.
#
# Inputs (wago.tools CSV exports): SpellAuraRestrictions, SkillLineAbility, TraitDefinition
# Run: python tools/gen_aura_requirements.py [csv_dir] [build]

import csv
import sys
from pathlib import Path

DEFAULT_CSV_DIR = Path(__file__).resolve().parent.parent / "Documentation" / "wow_spell_csv"


def read_csv(path):
    with open(path, encoding="utf-8-sig", newline="") as f:
        yield from csv.DictReader(f)


def main():
    csv_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV_DIR
    build = sys.argv[2] if len(sys.argv) > 2 else "12.1.0.68301"

    def find(table):
        hits = sorted(csv_dir.glob(f"{table}.*.csv"))
        if not hits:
            sys.exit(f"missing {table} csv in {csv_dir}")
        return hits[-1]

    universe = set()
    for row in read_csv(find("SkillLineAbility")):
        universe.add(int(row["Spell"]))
    for row in read_csv(find("TraitDefinition")):
        for col in ("SpellID", "VisibleSpellID", "OverridesSpellID"):
            v = int(row[col] or 0)
            if v > 0:
                universe.add(v)

    out = {}
    for row in read_csv(find("SpellAuraRestrictions")):
        if int(row["DifficultyID"] or 0) != 0:
            continue
        sid = int(row["SpellID"])
        required = int(row["CasterAuraSpell"] or 0)
        if required > 0 and sid in universe:
            out[sid] = required

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: Caster-aura requirements ([spellID] = aura spellID the player",
        "-- must have for the spell to be castable). The queue sinks these while",
        "-- the required aura is absent.",
        f"-- GENERATED by tools/gen_aura_requirements.py from client data build {build}.",
        "-- Do not hand-edit.",
        'local SpellDB = LibStub("JustAC-SpellDB", true)',
        "if not SpellDB or not SpellDB.RegisterAuraRequirements then return end",
        "",
        "SpellDB.RegisterAuraRequirements({",
    ]
    for sid in sorted(out):
        lines.append(f"[{sid}]={out[sid]},")
    lines += ["})", ""]

    out_path = Path(__file__).parent.parent / "Data" / "AuraRequirements.lua"
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{out_path}: {len(out)} aura-gated spells, universe {len(universe)}, build {build}")


if __name__ == "__main__":
    main()
