# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/FormRequirements.lua from client data CSV exports.
#
# Hard shapeshift requirements ([spellID] = stance mask, bit N = form ID N+1):
# lets the queue sink/hide form-gated abilities (cat attacks, bear-only
# defensives) via never-secret GetShapeshiftFormID() even in combat, where
# IsUsableSpell is secret.
#
# Only masks that are a pure subset of Cat Form (ID 1) + Bear Form (ID 5) are
# emitted. Client data can't reliably distinguish "requires these forms" from
# "also usable in these forms" for other masks (Moonfire carries a
# Moonkin+Tree mask yet casts unshifted; stealth masks are bypassed by
# Subterfuge/Shadow Dance windows) - cat/bear-only masks are empirically hard
# gates, everything else stays with the live usability checks. The
# SPELL_ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED exclusion is kept as a second belt.
# Auto-shift talents (Fluid Form) are handled at runtime in SpellDB.IsSpellFormGated.
#
# Inputs (wago.tools CSV exports): SpellShapeshift, SpellMisc, SkillLineAbility, TraitDefinition
# Run: python tools/gen_form_requirements.py [csv_dir] [build]

import csv
import sys
from pathlib import Path

DEFAULT_CSV_DIR = Path(__file__).resolve().parent.parent / "Documentation" / "wow_spell_csv"
ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED = 0x400
CAT_BEAR_MASK = (1 << 0) | (1 << 4)   # form IDs 1 (Cat) and 5 (Bear)
STEALTH_MASK = 1 << 29  # form ID 30 (Stealth) - NOT bit 30, that's Moonkin (form 31)


def read_csv(path):
    with open(path, encoding="utf-8-sig", newline="") as f:
        yield from csv.DictReader(f)


def main():
    csv_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV_DIR
    build = sys.argv[2] if len(sys.argv) > 2 else "12.1.0.68301"

    def find(table):
        hits = sorted(csv_dir.glob(f"{table}.*.csv"))
        if not hits:
            sys.exit(f"missing {table} csv in {csv_dir}")
        return hits[-1]

    universe = set()
    for row in read_csv(find("SkillLineAbility")):
        universe.add(int(row["Spell"]))
    for row in read_csv(find("TraitDefinition")):
        for col in ("SpellID", "VisibleSpellID", "OverridesSpellID"):
            v = int(row[col] or 0)
            if v > 0:
                universe.add(v)

    # Candidates: form masks that are a pure cat/bear subset, and stealth-only
    # masks (emitted separately - stealth gating needs runtime window checks)
    masks = {}
    stealth = {}
    for row in read_csv(find("SpellShapeshift")):
        sid = int(row["SpellID"])
        mask = int(row["ShapeshiftMask_0"] or 0) % 2**32
        if mask and sid in universe:
            if mask & ~CAT_BEAR_MASK == 0:
                masks[sid] = mask
            elif mask & ~STEALTH_MASK == 0:
                stealth[sid] = True

    # Drop candidates castable while unshifted (soft requirement)
    for row in read_csv(find("SpellMisc")):
        sid = int(row["SpellID"])
        if (sid in masks or sid in stealth) and int(row["DifficultyID"] or 0) == 0:
            if int(row["Attributes_2"] or 0) & ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED:
                masks.pop(sid, None)
                stealth.pop(sid, None)

    names = {int(r["ID"]): r["Name_lang"] for r in read_csv(find("SpellName"))}

    def nm(sid):
        return (names.get(sid) or "?").replace("\r", "").replace("\n", " ")

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: Hard shapeshift requirements ([spellID] = stance mask, bit N =",
        "-- usable in form ID N+1). Consumed via SpellDB.IsSpellFormGated to sink or",
        "-- hide form-gated abilities without secret-value reads.",
        f"-- GENERATED by tools/gen_form_requirements.py from client data build {build}.",
        "-- Do not hand-edit.",
        'local SpellDB = LibStub("JustAC-SpellDB", true)',
        "if not SpellDB or not SpellDB.RegisterFormRequirements then return end",
        "",
        "SpellDB.RegisterFormRequirements({",
    ]
    for sid in sorted(masks):
        lines.append(f"[{sid}]={masks[sid]},  -- {nm(sid)}")
    lines += [
        "})",
        "",
        "-- Stealth-required spells (stealth-only stance masks). Gated at runtime",
        "-- with IsStealthed() + stealth-window auras, never statically.",
        "if SpellDB.RegisterStealthRequirements then",
        "SpellDB.RegisterStealthRequirements({",
    ]
    for sid in sorted(stealth):
        lines.append(f"[{sid}]=true,  -- {nm(sid)}")
    lines += ["})", "end", ""]

    out_path = Path(__file__).parent.parent / "Data" / "FormRequirements.lua"
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{out_path}: {len(masks)} form-gated + {len(stealth)} stealth-required spells, "
          f"universe {len(universe)}, build {build}")


if __name__ == "__main__":
    main()
