# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 wealdly
# Generates Data/SpellCooldowns.lua from client data CSV exports.
#
# Static base cooldown/charge data for local cooldown tracking: runtime CD APIs
# (GetSpellBaseCooldown, tooltips, C_Spell.GetSpellCharges) are secret in combat,
# so a spell never seen out of combat has no duration and IsSpellReady fails open.
# This table is the in-combat last resort (base values, unmodified by talents).
#
# Inputs (same folder, wago.tools CSV exports):
#   SpellCooldowns.csv     - per-spell RecoveryTime / CategoryRecoveryTime
#   SpellCategories.csv    - per-spell ChargeCategory
#   SpellCategory.csv      - per-category MaxCharges / ChargeRecoveryTime
#   SkillLineAbility.csv   - player-learnable spell filter
#   TraitDefinition.csv    - talent spell filter
#
# Run: python tools/gen_spell_cooldowns.py [csv_dir] [build]
# (csv_dir defaults to Documentation/wow_spell_csv, same as the sibling generators)

import csv
import sys
from pathlib import Path

MIN_CD_MS = 3000  # matches MIN_TRACKABLE_CD_SECS in CooldownTracking.lua
DEFAULT_CSV_DIR = Path(__file__).resolve().parent.parent / "Documentation" / "wow_spell_csv"


def read_csv(path):
    with open(path, encoding="utf-8-sig", newline="") as f:
        yield from csv.DictReader(f)


def main():
    csv_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV_DIR
    build = sys.argv[2] if len(sys.argv) > 2 else "12.1.0.68301"

    def find(table):
        hits = sorted(csv_dir.glob(f"{table}.*.csv"))
        if not hits:
            sys.exit(f"missing {table} csv in {csv_dir}")
        return hits[-1]

    # Player-relevant spell universe: class/profession skill lines + talents
    universe = set()
    for row in read_csv(find("SkillLineAbility")):
        universe.add(int(row["Spell"]))
    for row in read_csv(find("TraitDefinition")):
        for col in ("SpellID", "VisibleSpellID", "OverridesSpellID"):
            v = int(row[col] or 0)
            if v > 0:
                universe.add(v)

    # Charge categories: ID -> (MaxCharges, ChargeRecoveryTime)
    categories = {}
    for row in read_csv(find("SpellCategory")):
        max_charges = int(row["MaxCharges"] or 0)
        recharge = int(row["ChargeRecoveryTime"] or 0)
        if max_charges >= 1 and recharge > 0:
            categories[int(row["ID"])] = (max_charges, recharge)

    # Per-spell charge assignment (base difficulty only)
    charges = {}
    for row in read_csv(find("SpellCategories")):
        if int(row["DifficultyID"] or 0) != 0:
            continue
        cat = categories.get(int(row["ChargeCategory"] or 0))
        if cat:
            charges[int(row["SpellID"])] = cat

    # Flat cooldowns (base difficulty only)
    flat = {}
    for row in read_csv(find("SpellCooldowns")):
        if int(row["DifficultyID"] or 0) != 0:
            continue
        eff = max(int(row["RecoveryTime"] or 0), int(row["CategoryRecoveryTime"] or 0))
        if eff > 0:
            flat[int(row["SpellID"])] = eff

    # Merge: charge spells (max > 1) emit {max, rechargeMs}; single-charge spells
    # are flat cooldowns implemented as charges - fold into the flat value.
    out = {}
    for sid in universe:
        cd = flat.get(sid, 0)
        ch = charges.get(sid)
        if ch and ch[0] > 1:
            if ch[1] >= MIN_CD_MS:
                out[sid] = ch
            continue
        if ch:  # single charge: recharge acts as the cooldown
            cd = max(cd, ch[1])
        if cd >= MIN_CD_MS:
            out[sid] = cd

    names = {int(r["ID"]): r["Name_lang"] for r in read_csv(find("SpellName"))}

    def nm(sid):
        return (names.get(sid) or "?").replace("\r", "").replace("\n", " ")

    lines = [
        "-- SPDX-License-Identifier: GPL-3.0-or-later",
        "-- Copyright (C) 2024-2026 wealdly",
        "-- JustAC: Static base cooldown/charge data (in-combat last resort for local",
        "-- cooldown tracking; runtime CD APIs are secret in combat).",
        f"-- GENERATED by tools/gen_spell_cooldowns.py from client data build {build}.",
        "-- Do not hand-edit. Flat entry: [spellID] = cooldownMs.",
        "-- Charge entry: [spellID] = {maxCharges, rechargeMs}.",
        'local lib = LibStub:NewLibrary("JustAC-CooldownData", 1)',
        "if not lib then return end",
        "",
        "local D = {",
    ]
    for sid in sorted(out):
        v = out[sid]
        if isinstance(v, tuple):
            lines.append(f"[{sid}]={{{v[0]},{v[1]}}},  -- {nm(sid)}")
        else:
            lines.append(f"[{sid}]={v},  -- {nm(sid)}")
    lines += [
        "}",
        "",
        "--- @return number|nil cooldownMs, number|nil maxCharges, number|nil rechargeMs",
        "function lib.Get(spellID)",
        "    local v = D[spellID]",
        "    if not v then return nil end",
        '    if type(v) == "table" then return nil, v[1], v[2] end',
        "    return v",
        "end",
        "",
    ]

    out_path = Path(__file__).parent.parent / "Data" / "SpellCooldowns.lua"
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    n_charge = sum(1 for v in out.values() if isinstance(v, tuple))
    print(f"{out_path}: {len(out)} spells ({n_charge} charge-based), "
          f"universe {len(universe)}, build {build}")


if __name__ == "__main__":
    main()
